import {
  use as registerEChartsModules,
  init,
  dispose,
  registerTheme,
  type EChartsType,
} from 'echarts/core';
import { resolveFluxEChartsTheme } from './echarts-theme.js';
import {
  LineChart,
  BarChart,
  ScatterChart,
  EffectScatterChart,
  PieChart,
  RadarChart,
  FunnelChart,
  GaugeChart,
  SankeyChart,
  TreemapChart,
  TreeChart,
  BoxplotChart,
  CandlestickChart,
  GraphChart,
  SunburstChart,
  ThemeRiverChart,
  ParallelChart,
  PictorialBarChart,
  LinesChart,
  HeatmapChart,
  MapChart,
  CustomChart,
} from 'echarts/charts';
import {
  TitleComponent,
  TooltipComponent,
  GridComponent,
  LegendComponent,
  DatasetComponent,
  TransformComponent,
  ToolboxComponent,
  DataZoomComponent,
  VisualMapComponent,
  MarkLineComponent,
  MarkPointComponent,
  MarkAreaComponent,
  GraphicComponent,
  AriaComponent,
  AxisPointerComponent,
  PolarComponent,
  RadarComponent,
  GeoComponent,
  ParallelComponent,
  SingleAxisComponent,
  TimelineComponent,
  CalendarComponent,
} from 'echarts/components';
import { CanvasRenderer, SVGRenderer } from 'echarts/renderers';

registerTheme('flux', resolveFluxEChartsTheme());

registerEChartsModules([
  LineChart,
  BarChart,
  ScatterChart,
  EffectScatterChart,
  PieChart,
  RadarChart,
  FunnelChart,
  GaugeChart,
  SankeyChart,
  TreemapChart,
  TreeChart,
  BoxplotChart,
  CandlestickChart,
  GraphChart,
  SunburstChart,
  ThemeRiverChart,
  ParallelChart,
  PictorialBarChart,
  LinesChart,
  HeatmapChart,
  MapChart,
  CustomChart,
  TitleComponent,
  TooltipComponent,
  GridComponent,
  LegendComponent,
  DatasetComponent,
  TransformComponent,
  ToolboxComponent,
  DataZoomComponent,
  VisualMapComponent,
  MarkLineComponent,
  MarkPointComponent,
  MarkAreaComponent,
  GraphicComponent,
  AriaComponent,
  AxisPointerComponent,
  PolarComponent,
  RadarComponent,
  GeoComponent,
  ParallelComponent,
  SingleAxisComponent,
  TimelineComponent,
  CalendarComponent,
  CanvasRenderer,
  SVGRenderer,
]);

export function getECharts() {
  return { init, dispose };
}

export type { EChartsType };
