import type { RendererDefinition } from '@nop-chaos/flux-core';
import type { GanttSchema, KanbanSchema, CalendarSchema } from './schemas.js';

export const schedulingRendererDefinitions: RendererDefinition[] = [
  {
    type: 'gantt',
    displayName: 'Gantt',
    category: 'scheduling',
    sourcePackage: '@nop-chaos/flux-renderers-scheduling',
    defaultSchema: { type: 'gantt', body: [] },
    component: () => null,
    fields: [
      { key: 'body', kind: 'region', regionKey: 'body' },
      { key: 'tasks', kind: 'prop' },
      { key: 'links', kind: 'prop' },
      { key: 'resources', kind: 'prop' },
      { key: 'assignments', kind: 'prop' },
      { key: 'columns', kind: 'prop' },
      { key: 'scales', kind: 'prop' },
      { key: 'zoomLevels', kind: 'prop' },
      { key: 'defaultZoom', kind: 'prop' },
      { key: 'cellWidth', kind: 'prop' },
      { key: 'startDate', kind: 'prop' },
      { key: 'endDate', kind: 'prop' },
      { key: 'taskBarHeight', kind: 'prop' },
      { key: 'progressBarHeight', kind: 'prop' },
      { key: 'showWeekends', kind: 'prop' },
      { key: 'showToday', kind: 'prop' },
      { key: 'draggable', kind: 'prop' },
      { key: 'editable', kind: 'prop' },
      { key: 'linkable', kind: 'prop' },
      { key: 'calendar', kind: 'prop' },
      { key: 'taskBar', kind: 'region', regionKey: 'taskBar' },
      { key: 'toolbar', kind: 'region', regionKey: 'toolbar' },
      { key: 'editor', kind: 'region', regionKey: 'editor' },
      { key: 'empty', kind: 'region', regionKey: 'empty' },
      { key: 'loading', kind: 'region', regionKey: 'loading' },
      { key: 'onTaskClick', kind: 'event' },
      { key: 'onTaskDoubleClick', kind: 'event' },
      { key: 'onTaskDragEnd', kind: 'event' },
      { key: 'onLinkClick', kind: 'event' },
      { key: 'onLinkDragEnd', kind: 'event' },
      { key: 'onEmptyCellClick', kind: 'event' },
      { key: 'onZoomChange', kind: 'event' },
      { key: 'onScroll', kind: 'event' },
      { key: 'zoomIn', kind: 'reaction' },
      { key: 'zoomOut', kind: 'reaction' },
      { key: 'scrollToToday', kind: 'reaction' },
      { key: 'scrollToTask', kind: 'reaction' },
    ],
  },
  {
    type: 'kanban',
    displayName: 'Kanban',
    category: 'scheduling',
    sourcePackage: '@nop-chaos/flux-renderers-scheduling',
    defaultSchema: { type: 'kanban', body: [] },
    component: () => null,
    fields: [
      { key: 'body', kind: 'region', regionKey: 'body' },
    ],
  },
  {
    type: 'calendar',
    displayName: 'Calendar',
    category: 'scheduling',
    sourcePackage: '@nop-chaos/flux-renderers-scheduling',
    defaultSchema: { type: 'calendar', body: [] },
    component: () => null,
    fields: [
      { key: 'body', kind: 'region', regionKey: 'body' },
      { key: 'events', kind: 'prop' },
      { key: 'resources', kind: 'prop' },
      { key: 'onEventChange', kind: 'event' },
    ],
  },
];

export type SchedulingRendererSchema = GanttSchema | KanbanSchema | CalendarSchema;
