import type { RendererDefinition } from '@nop-chaos/flux-core';
import type { GanttSchema, KanbanSchema, CalendarSchema, BarcodeInputSchema } from './schemas.js';
import { Calendar } from './calendar/calendar.js';
import { Gantt } from './gantt/gantt.js';
import { KanbanBoard } from './kanban/kanban-board.js';
import { BarcodeInputRenderer } from './barcode-input/barcode-input.js';
import { barcodeInputFieldRules } from './barcode-input/barcode-input-schemas.js';

export const schedulingRendererDefinitions: RendererDefinition[] = [
  {
    type: 'gantt',
    displayName: 'Gantt',
    category: 'scheduling',
    sourcePackage: '@nop-chaos/flux-renderers-scheduling',
    defaultSchema: { type: 'gantt', body: [] },
    component: Gantt,
    fields: [
      { key: 'body', kind: 'region', regionKey: 'body' },
      { key: 'tasks', kind: 'prop' },
      { key: 'links', kind: 'prop' },
      { key: 'resources', kind: 'prop' },
      { key: 'assignments', kind: 'prop' },
      { key: 'columns', kind: 'prop' },
      { key: 'scales', kind: 'prop' },
      { key: 'zoomLevels', kind: 'prop' },
      { key: 'defaultZoom', kind: 'prop' },
      { key: 'cellWidth', kind: 'prop' },
      { key: 'startDate', kind: 'prop' },
      { key: 'endDate', kind: 'prop' },
      { key: 'taskBarHeight', kind: 'prop' },
      { key: 'progressBarHeight', kind: 'prop' },
      { key: 'showWeekends', kind: 'prop' },
      { key: 'showToday', kind: 'prop' },
      { key: 'draggable', kind: 'prop' },
      { key: 'editable', kind: 'prop' },
      { key: 'linkable', kind: 'prop' },
      { key: 'calendar', kind: 'prop' },
      { key: 'taskBar', kind: 'region', regionKey: 'taskBar' },
      { key: 'toolbar', kind: 'region', regionKey: 'toolbar' },
      { key: 'editor', kind: 'region', regionKey: 'editor' },
      { key: 'empty', kind: 'region', regionKey: 'empty' },
      { key: 'loading', kind: 'region', regionKey: 'loading' },
      { key: 'onTaskClick', kind: 'event' },
      { key: 'onTaskDoubleClick', kind: 'event' },
      { key: 'onTaskDragEnd', kind: 'event' },
      { key: 'onLinkClick', kind: 'event' },
      { key: 'onLinkDragEnd', kind: 'event' },
      { key: 'onEmptyCellClick', kind: 'event' },
      { key: 'onZoomChange', kind: 'event' },
      { key: 'onScroll', kind: 'event' },
      { key: 'onMount', kind: 'meta' },
      { key: 'onUnmount', kind: 'meta' },
      { key: 'childrenField', kind: 'prop' },
      { key: 'initiallyExpanded', kind: 'prop' },
      { key: 'toolbarClassName', kind: 'prop' },
      { key: 'taskBarClassName', kind: 'prop' },
      { key: 'editorClassName', kind: 'prop' },
      { key: 'emptyClassName', kind: 'prop' },
      { key: 'zoomIn', kind: 'reaction' },
      { key: 'zoomOut', kind: 'reaction' },
      { key: 'scrollToToday', kind: 'reaction' },
      { key: 'scrollToTask', kind: 'reaction' },
    ],
  },
  {
    type: 'kanban',
    displayName: 'Kanban',
    category: 'scheduling',
    sourcePackage: '@nop-chaos/flux-renderers-scheduling',
    defaultSchema: { type: 'kanban', body: [] },
    component: KanbanBoard,
    fields: [
      { key: 'body', kind: 'region', regionKey: 'body' },
      { key: 'data', kind: 'prop' },
      { key: 'configMap', kind: 'prop' },
      // consumed: used as data-driven columns configuration
      { key: 'columnsConfig', kind: 'prop' },
      { key: 'columnHeader', kind: 'region', regionKey: 'columnHeader' },
      { key: 'columnHeaderToolbar', kind: 'region', regionKey: 'columnHeaderToolbar' },
      { key: 'cardTemplate', kind: 'region', regionKey: 'cardTemplate' },
      { key: 'columnFooter', kind: 'region', regionKey: 'columnFooter' },
      { key: 'empty', kind: 'region', regionKey: 'empty' },
      { key: 'loading', kind: 'region', regionKey: 'loading' },
      { key: 'filterText', kind: 'prop' },
      { key: 'filterCard', kind: 'prop' },
      { key: 'columnWidth', kind: 'prop' },
      { key: 'columnDraggable', kind: 'prop' },
      { key: 'draggable', kind: 'prop' },
      { key: 'columnsOrderStatePath', kind: 'prop' },
      { key: 'columnsOrderOwnership', kind: 'prop' },
      { key: 'collapsedStatePath', kind: 'prop' },
      { key: 'collapsedOwnership', kind: 'prop' },
      // consumed: applied to KanbanColumn sub-elements
      { key: 'columnHeaderClassName', kind: 'prop' },
      { key: 'cardClassName', kind: 'prop' },
      { key: 'columnFooterClassName', kind: 'prop' },
      // reserved: future controlled-mode support
      { key: 'kanbanOwnership', kind: 'prop' },
      { key: 'kanbanStatePath', kind: 'prop' },
      { key: 'statusPath', kind: 'prop' },
      { key: 'onMount', kind: 'meta' },
      { key: 'onUnmount', kind: 'meta' },
      { key: 'onCardMove', kind: 'event' },
      { key: 'onCardClick', kind: 'event' },
      { key: 'onColumnReorder', kind: 'event' },
      { key: 'onColumnClick', kind: 'event' },
      { key: 'onCardAdd', kind: 'event' },
      { key: 'onCardRemove', kind: 'event' },
    ],
  },
  {
    type: 'calendar',
    displayName: 'Calendar',
    category: 'scheduling',
    sourcePackage: '@nop-chaos/flux-renderers-scheduling',
    defaultSchema: { type: 'calendar', view: 'month' },
    component: Calendar,
    fields: [
      { key: 'view', kind: 'prop' },
      { key: 'date', kind: 'prop' },
      { key: 'events', kind: 'prop' },
      { key: 'resources', kind: 'prop' },
      { key: 'firstDayOfWeek', kind: 'prop' },
      { key: 'showWeekends', kind: 'prop' },
      { key: 'maxConcurrent', kind: 'prop' },
      { key: 'eventTemplate', kind: 'region', regionKey: 'eventTemplate' },
      { key: 'loading', kind: 'region', regionKey: 'loading' },
      { key: 'empty', kind: 'region', regionKey: 'empty' },
      { key: 'body', kind: 'region', regionKey: 'body' },
      { key: 'headerClassName', kind: 'prop' },
      { key: 'eventClassName', kind: 'prop' },
      { key: 'emptyClassName', kind: 'prop' },
      { key: 'onEventClick', kind: 'event' },
      { key: 'onDateChange', kind: 'event' },
      { key: 'onViewChange', kind: 'event' },
      { key: 'onEventChange', kind: 'event' },
      // Sole creation channel for drag-create; onEventChange is NOT fired during creation.
      { key: 'onEventCreate', kind: 'event' },
      { key: 'onBatchSchedule', kind: 'event' },
      { key: 'onImport', kind: 'event' },
      { key: 'onImportError', kind: 'event' },
      { key: 'onTimezoneChange', kind: 'event' },
      { key: 'onGroupToggle', kind: 'event' },
      { key: 'showCrossDayLines', kind: 'prop' },
      { key: 'timezoneSelector', kind: 'prop' },
      { key: 'batchScheduling', kind: 'prop' },
      { key: 'resources[].resources', kind: 'prop' },
      { key: 'resources[].open', kind: 'prop' },
      { key: 'viewOwnership', kind: 'prop' },
      { key: 'viewStatePath', kind: 'prop' },
      { key: 'dateOwnership', kind: 'prop' },
      { key: 'dateStatePath', kind: 'prop' },
      { key: 'statusPath', kind: 'prop' },
      { key: 'loadAction', kind: 'event' },
      { key: 'onMount', kind: 'meta' },
      { key: 'onUnmount', kind: 'meta' },
      { key: 'component:print', kind: 'reaction' },
      { key: 'component:exportPNG', kind: 'reaction' },
      { key: 'component:importICal', kind: 'reaction' },
      { key: 'component:exportToICal', kind: 'reaction' },
    ],
  },
  {
    type: 'barcode-input',
    displayName: 'Barcode Input',
    category: 'scheduling',
    sourcePackage: '@nop-chaos/flux-renderers-scheduling',
    defaultSchema: { type: 'barcode-input', name: 'barcode' },
    component: BarcodeInputRenderer,
    fields: barcodeInputFieldRules,
    wrap: true,
  },
];

export type SchedulingRendererSchema = GanttSchema | KanbanSchema | CalendarSchema | BarcodeInputSchema;
