import { expect, test } from '@playwright/test';

async function openFlowDesigner(page: import('@playwright/test').Page) {
  await page.goto('/');
  await page.getByRole('button', { name: 'Flow Designer' }).click();
  await page.waitForTimeout(3000);
}

test('diagnoses layout CSS: height chain from viewport to ReactFlow', async ({ page }) => {
  await openFlowDesigner(page);

  const diag = await page.evaluate(() => {
    const rfWrapper = document.querySelector('[data-testid="rf__wrapper"]');
    const rfSurface = rfWrapper?.parentElement;
    const canvasSlot = rfSurface?.parentElement;
    const threeColGrid = canvasSlot?.parentElement;
    const outerGrid = threeColGrid?.parentElement;

    const results: Record<string, any> = {};

    const measure = (label: string, el: HTMLElement | null | undefined) => {
      if (!el) {
        results[label] = { ERROR: 'element not found' };
        return;
      }
      const cs = window.getComputedStyle(el);
      const rect = el.getBoundingClientRect();
      results[label] = {
        tagName: el.tagName,
        className: el.className,
        position: cs.position,
        width: cs.width,
        height: cs.height,
        top: cs.top,
        left: cs.left,
        right: cs.right,
        bottom: cs.bottom,
        inset: cs.inset,
        overflow: cs.overflow,
        display: cs.display,
        rectW: rect.width,
        rectH: rect.height,
        rectTop: rect.top,
        rectLeft: rect.left,
      };
    };

    measure('1_RootContainer', outerGrid as HTMLElement | null);
    measure('2_ThreeColGrid', threeColGrid as HTMLElement | null);
    measure('3_CanvasSlot', canvasSlot as HTMLElement | null);
    measure('4_RfSurface', rfSurface as HTMLElement | null);
    measure('5_RfWrapper', rfWrapper as HTMLElement | null);

    return results;
  });

  console.log('=== LAYOUT DIAGNOSTICS ===');
  for (const [label, info] of Object.entries(diag)) {
    console.log(`\n--- ${label} ---`);
    if ((info as any).ERROR) {
      console.log(`  ERROR: ${(info as any).ERROR}`);
      continue;
    }
    const i = info as any;
    console.log(`  tag=${i.tagName}  class="${i.className?.substring(0, 120)}"`);
    console.log(`  display=${i.display}  position=${i.position}`);
    console.log(`  computed: ${i.width} x ${i.height}`);
    console.log(`  rect:     ${i.rectW} x ${i.rectH}  (top=${i.rectTop}, left=${i.rectLeft})`);
  }

  expect(diag['1_RootContainer']).not.toHaveProperty('ERROR');
  expect(diag['2_ThreeColGrid']).not.toHaveProperty('ERROR');
  expect(diag['3_CanvasSlot']).not.toHaveProperty('ERROR');
  expect(diag['4_RfSurface']).not.toHaveProperty('ERROR');
  expect(diag['5_RfWrapper']).not.toHaveProperty('ERROR');

  const rootH = parseFloat((diag['1_RootContainer'] as any).height);
  expect(rootH).toBeGreaterThan(100);

  const threeColH = parseFloat((diag['2_ThreeColGrid'] as any).height);
  expect(threeColH).toBeGreaterThan(100);

  const canvasSlotH = parseFloat((diag['3_CanvasSlot'] as any).rectH);
  expect(canvasSlotH).toBeGreaterThan(100);

  const rfSurfaceH = parseFloat((diag['4_RfSurface'] as any).rectH);
  expect(rfSurfaceH).toBeGreaterThan(100);

  const rfWrapperH = parseFloat((diag['5_RfWrapper'] as any).rectH);
  expect(rfWrapperH).toBeGreaterThan(100);
});

test('checks Tailwind CSS generation for layout classes', async ({ page }) => {
  await openFlowDesigner(page);

  const cssChecks = await page.evaluate(() => {
    const results: Record<string, { found: boolean; value: string }> = {};

    const test = document.createElement('div');

    const classesToCheck = [
      'absolute',
      'relative',
      'inset-0',
      'h-full',
      'w-full',
      'min-h-0',
      'overflow-hidden',
      'grid',
      'grid-rows-[auto_minmax(0,1fr)]',
      'grid-cols-[15rem_minmax(0,1fr)_22rem]',
      'gap-3',
      'p-6',
      'rounded-xl',
      'border',
      'border-border',
      'shadow-sm',
      'text-foreground',
    ];

    for (const cls of classesToCheck) {
      test.className = cls;
      document.body.appendChild(test);
      const cs = window.getComputedStyle(test);
      const hasEffect = cs.cssText.length > 0;
      results[cls] = { found: hasEffect, value: cs.cssText.substring(0, 100) };
      document.body.removeChild(test);
    }

    return results;
  });

  console.log('=== TAILWIND CSS GENERATION CHECK ===');
  for (const [cls, info] of Object.entries(cssChecks)) {
    const status = info.found ? 'OK' : 'MISSING';
    console.log(`  [${status}] .${cls}`);
    if (info.value) {
      console.log(`         -> ${info.value}`);
    }
  }

  const missing = Object.entries(cssChecks).filter(([, v]) => !v.found);
  if (missing.length > 0) {
    console.log(`\n!! ${missing.length} classes not generated by Tailwind:`);
    for (const [cls] of missing) {
      console.log(`  - .${cls}`);
    }
  }
});

test('checks specific CSS properties on canvas slot and children', async ({ page }) => {
  await openFlowDesigner(page);

  const props = await page.evaluate(() => {
    const canvasSlot = document.querySelector('.nop-designer__canvas') as HTMLElement | null
      ?? document.querySelector('.react-flow')?.closest('.relative') as HTMLElement | null;
    if (!canvasSlot) {
      return { error: 'canvas slot not found' };
    }

    const cs = window.getComputedStyle(canvasSlot);
    const slotInfo = {
      className: canvasSlot.className,
      position: cs.position,
      width: cs.width,
      height: cs.height,
      overflow: cs.overflow,
      display: cs.display,
      rectW: canvasSlot.getBoundingClientRect().width,
      rectH: canvasSlot.getBoundingClientRect().height,
    };

    const rfSurface = canvasSlot.querySelector('.fd-xyflow-surface') as HTMLElement | null
      ?? canvasSlot.querySelector('.nop-designer-node') as HTMLElement | null
      ?? canvasSlot.firstElementChild as HTMLElement | null;
    const surfaceInfo = rfSurface ? (() => {
      const scs = window.getComputedStyle(rfSurface);
      return {
        className: rfSurface.className,
        position: scs.position,
        width: scs.width,
        height: scs.height,
        top: scs.top,
        left: scs.left,
        right: scs.right,
        bottom: scs.bottom,
        rectW: rfSurface.getBoundingClientRect().width,
        rectH: rfSurface.getBoundingClientRect().height,
      };
    })() : { error: 'no surface child' };

    const rfWrapper = document.querySelector('[data-testid="rf__wrapper"]') as HTMLElement | null;
    const rfInfo = rfWrapper ? (() => {
      const rcs = window.getComputedStyle(rfWrapper);
      return {
        className: rfWrapper.className?.substring(0, 80),
        position: rcs.position,
        width: rcs.width,
        height: rcs.height,
        rectW: rfWrapper.getBoundingClientRect().width,
        rectH: rfWrapper.getBoundingClientRect().height,
      };
    })() : { error: 'rf__wrapper not found' };

    return { slotInfo, surfaceInfo, rfInfo };
  });

  console.log('=== CANVAS SLOT PROPERTIES ===');
  console.log(JSON.stringify(props, null, 2));

  expect(props).not.toHaveProperty('error');
  const slot = (props as any).slotInfo;
  expect(slot.rectH).toBeGreaterThan(100);

  const surface = (props as any).surfaceInfo;
  if (!surface.error) {
    expect(surface.rectH).toBeGreaterThan(100);
  }

  const rf = (props as any).rfInfo;
  if (!rf.error) {
    expect(rf.rectH).toBeGreaterThan(100);
  }
});

test('dumps console warnings for React Flow error 004', async ({ page }) => {
  const warnings: string[] = [];
  page.on('console', (msg) => {
    if (msg.text().includes('React Flow') || msg.text().includes('004') || msg.text().includes('width and a height')) {
      warnings.push(msg.text());
    }
  });

  await openFlowDesigner(page);

  if (warnings.length > 0) {
    console.log('=== REACT FLOW WARNINGS ===');
    for (const w of warnings) {
      console.log(`  ${w}`);
    }
  }

  expect(warnings).toHaveLength(0);
});

test('verifies canvas layout with Tailwind classes', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Flow Designer' }).click();
  await page.waitForTimeout(3000);

  const checks = await page.evaluate(() => {
    const results: Record<string, any> = {};

    const rfWrapper = document.querySelector('[data-testid="rf__wrapper"]') as HTMLElement | null;
    if (rfWrapper) {
      const rect = rfWrapper.getBoundingClientRect();
      results.rfWrapper = { width: rect.width, height: rect.height };
    } else {
      results.rfWrapper = { error: 'rf__wrapper not found' };
    }

    const canvasSlot = rfWrapper?.closest('[class*="relative"]') as HTMLElement | null;
    if (canvasSlot) {
      results.canvasSlot = {
        height: canvasSlot.getBoundingClientRect().height,
        width: canvasSlot.getBoundingClientRect().width,
      };
    }

    return results;
  });

  console.log(JSON.stringify(checks, null, 2));

  expect((checks.rfWrapper as any).height).toBeGreaterThan(100);
  expect((checks.canvasSlot as any).height).toBeGreaterThan(100);
});

test('dumps full DOM hierarchy from body to ReactFlow for debugging', async ({ page }) => {
  await openFlowDesigner(page);

  const hierarchy = await page.evaluate(() => {
    const rf = document.querySelector('[data-testid="rf__wrapper"]');
    if (!rf) return { error: 'rf__wrapper not found' };

    const chain: string[] = [];
    let el: HTMLElement | null = rf as HTMLElement;
    while (el && el !== document.body) {
      const cs = window.getComputedStyle(el);
      const rect = el.getBoundingClientRect();
      chain.push(
        `<${el.tagName.toLowerCase()}` +
        ` class="${(el.className || '').toString().substring(0, 120)}"` +
        ` position="${cs.position}"` +
        ` w="${cs.width}" h="${cs.height}"` +
        ` rectW="${rect.width.toFixed(1)}" rectH="${rect.height.toFixed(1)}"` +
        ` display="${cs.display}"` +
        ` overflow="${cs.overflow}">`
      );
      el = el.parentElement;
    }
    chain.reverse();
    return chain;
  });

  console.log('=== DOM HIERARCHY (body -> rf__wrapper) ===');
  if (Array.isArray(hierarchy)) {
    for (const line of hierarchy) {
      console.log(line);
    }
  } else {
    console.log(hierarchy);
  }
});
