import React from 'react';
import {
  PageLabPage,
  ContainerLabPage,
  FragmentLabPage,
  FlexLabPage,
  DialogLabPage,
  DrawerLabPage,
  TabsLabPage,
  LoopLabPage,
  RecurseLabPage,
  TextLabPage,
  IconLabPage,
  BadgeLabPage,
  ButtonLabPage,
  ScopeDebugLabPage,
  DynamicRendererLabPage,
  ReactionLabPage,
  FormLabPage,
  InputTextLabPage,
  InputEmailLabPage,
  InputPasswordLabPage,
  InputNumberLabPage,
  TextareaLabPage,
  SelectLabPage,
  CheckboxLabPage,
  SwitchLabPage,
  RadioGroupLabPage,
  CheckboxGroupLabPage,
  ButtonGroupSelectLabPage,
  FieldsetLabPage,
  HiddenLabPage,
  InputTreeLabPage,
  TreeSelectLabPage,
  TagListLabPage,
  KeyValueLabPage,
  ArrayEditorLabPage,
  ComboLabPage,
  InputTableLabPage,
  TransferLabPage,
  PickerLabPage,
  IconPickerLabPage,
  ConditionBuilderLabPage,
  ObjectFieldLabPage,
  ArrayFieldLabPage,
  VariantFieldLabPage,
  DetailFieldLabPage,
  DetailViewLabPage,
  CrudLabPage,
  TableLabPage,
  TreeLabPage,
  DataSourceLabPage,
  ChartLabPage,
  ListLabPage,
  PaginationLabPage,
  StatisticsLabPage,
  InputDateLabPage,
  InputDatetimeLabPage,
  InputTimeLabPage,
  DateRangeLabPage,
  InputMonthLabPage,
  InputQuarterLabPage,
  InputYearLabPage,
  MarkdownEditorLabPage,
  InputFileLabPage,
  InputImageLabPage,
  EditorLabPage,
  GridLabPage,
  CollapseLabPage,
  WizardLabPage,
  ButtonGroupLabPage,
  DropdownButtonLabPage,
  StepsLabPage,
  TimelineLabPage,
  MarkdownLabPage,
  HtmlLabPage,
  JsonViewLabPage,
  LinkLabPage,
  ImageLabPage,
  CardLabPage,
  CardsLabPage,
  EmptyLabPage,
  ProgressLabPage,
  SpinnerLabPage,
  SeparatorLabPage,
  AlertLabPage,
  MappingLabPage,
  StatusLabPage,
  AudioLabPage,
  VideoLabPage,
  CarouselLabPage,
  QrcodeLabPage,
  DiffViewLabPage,
  PullRefreshLabPage,
  InfiniteScrollLabPage,
  SwipeCellLabPage,
  CountdownLabPage,
  NoticeBarLabPage,
} from './renderers';

export const RENDERER_LAB_REGISTRY: Record<string, React.ComponentType> = {
  page: PageLabPage,
  container: ContainerLabPage,
  fragment: FragmentLabPage,
  flex: FlexLabPage,
  dialog: DialogLabPage,
  drawer: DrawerLabPage,
  tabs: TabsLabPage,
  loop: LoopLabPage,
  recurse: RecurseLabPage,
  text: TextLabPage,
  icon: IconLabPage,
  badge: BadgeLabPage,
  button: ButtonLabPage,
  'scope-debug': ScopeDebugLabPage,
  'dynamic-renderer': DynamicRendererLabPage,
  reaction: ReactionLabPage,
  form: FormLabPage,
  'input-text': InputTextLabPage,
  'input-email': InputEmailLabPage,
  'input-password': InputPasswordLabPage,
  'input-number': InputNumberLabPage,
  textarea: TextareaLabPage,
  select: SelectLabPage,
  checkbox: CheckboxLabPage,
  switch: SwitchLabPage,
  'radio-group': RadioGroupLabPage,
  'checkbox-group': CheckboxGroupLabPage,
  'button-group-select': ButtonGroupSelectLabPage,
  fieldset: FieldsetLabPage,
  hidden: HiddenLabPage,
  'input-tree': InputTreeLabPage,
  'tree-select': TreeSelectLabPage,
  'tag-list': TagListLabPage,
  'key-value': KeyValueLabPage,
  'array-editor': ArrayEditorLabPage,
  combo: ComboLabPage,
  'input-table': InputTableLabPage,
  transfer: TransferLabPage,
  picker: PickerLabPage,
  'icon-picker': IconPickerLabPage,
  'condition-builder': ConditionBuilderLabPage,
  'object-field': ObjectFieldLabPage,
  'array-field': ArrayFieldLabPage,
  'variant-field': VariantFieldLabPage,
  'detail-field': DetailFieldLabPage,
  'detail-view': DetailViewLabPage,
  crud: CrudLabPage,
  table: TableLabPage,
  tree: TreeLabPage,
  'data-source': DataSourceLabPage,
  chart: ChartLabPage,
  list: ListLabPage,
  pagination: PaginationLabPage,
  statistics: StatisticsLabPage,
  'input-date': InputDateLabPage,
  'input-datetime': InputDatetimeLabPage,
  'input-time': InputTimeLabPage,
  'date-range': DateRangeLabPage,
  'input-month': InputMonthLabPage,
  'input-quarter': InputQuarterLabPage,
  'input-year': InputYearLabPage,
  'markdown-editor': MarkdownEditorLabPage,
  'input-file': InputFileLabPage,
  'input-image': InputImageLabPage,
  editor: EditorLabPage,
  grid: GridLabPage,
  collapse: CollapseLabPage,
  wizard: WizardLabPage,
  'button-group': ButtonGroupLabPage,
  'dropdown-button': DropdownButtonLabPage,
  steps: StepsLabPage,
  timeline: TimelineLabPage,
  markdown: MarkdownLabPage,
  html: HtmlLabPage,
  'json-view': JsonViewLabPage,
  link: LinkLabPage,
  image: ImageLabPage,
  card: CardLabPage,
  cards: CardsLabPage,
  empty: EmptyLabPage,
  progress: ProgressLabPage,
  spinner: SpinnerLabPage,
  separator: SeparatorLabPage,
  alert: AlertLabPage,
  mapping: MappingLabPage,
  status: StatusLabPage,
  audio: AudioLabPage,
  video: VideoLabPage,
  carousel: CarouselLabPage,
  qrcode: QrcodeLabPage,
  'diff-view': DiffViewLabPage,
  'pull-refresh': PullRefreshLabPage,
  'infinite-scroll': InfiniteScrollLabPage,
  'swipe-cell': SwipeCellLabPage,
  countdown: CountdownLabPage,
  'notice-bar': NoticeBarLabPage,
};
