import React from 'react';
import {
  PageLabPage,
  ContainerLabPage,
  FragmentLabPage,
  FlexLabPage,
  DialogLabPage,
  DrawerLabPage,
  TabsLabPage,
  LoopLabPage,
  RecurseLabPage,
  TextLabPage,
  IconLabPage,
  BadgeLabPage,
  ButtonLabPage,
  ScopeDebugLabPage,
  DynamicRendererLabPage,
  ReactionLabPage,
  FormLabPage,
  InputTextLabPage,
  InputEmailLabPage,
  InputPasswordLabPage,
  InputNumberLabPage,
  TextareaLabPage,
  SelectLabPage,
  CheckboxLabPage,
  SwitchLabPage,
  RadioGroupLabPage,
  CheckboxGroupLabPage,
  FieldsetLabPage,
  InputTreeLabPage,
  TreeSelectLabPage,
  TagListLabPage,
  KeyValueLabPage,
  ArrayEditorLabPage,
  ComboLabPage,
  InputTableLabPage,
  TransferLabPage,
  PickerLabPage,
  ConditionBuilderLabPage,
  ObjectFieldLabPage,
  ArrayFieldLabPage,
  VariantFieldLabPage,
  DetailFieldLabPage,
  DetailViewLabPage,
  CrudLabPage,
  TableLabPage,
  TreeLabPage,
  DataSourceLabPage,
  ChartLabPage,
  ListLabPage,
  PaginationLabPage,
  StatisticsLabPage,
  InputDateLabPage,
  InputDatetimeLabPage,
  InputTimeLabPage,
  DateRangeLabPage,
  InputMonthLabPage,
  InputQuarterLabPage,
  InputYearLabPage,
  MarkdownEditorLabPage,
  InputFileLabPage,
  InputImageLabPage,
  EditorLabPage,
} from './renderers';

export const RENDERER_LAB_REGISTRY: Record<string, React.ComponentType> = {
  page: PageLabPage,
  container: ContainerLabPage,
  fragment: FragmentLabPage,
  flex: FlexLabPage,
  dialog: DialogLabPage,
  drawer: DrawerLabPage,
  tabs: TabsLabPage,
  loop: LoopLabPage,
  recurse: RecurseLabPage,
  text: TextLabPage,
  icon: IconLabPage,
  badge: BadgeLabPage,
  button: ButtonLabPage,
  'scope-debug': ScopeDebugLabPage,
  'dynamic-renderer': DynamicRendererLabPage,
  reaction: ReactionLabPage,
  form: FormLabPage,
  'input-text': InputTextLabPage,
  'input-email': InputEmailLabPage,
  'input-password': InputPasswordLabPage,
  'input-number': InputNumberLabPage,
  textarea: TextareaLabPage,
  select: SelectLabPage,
  checkbox: CheckboxLabPage,
  switch: SwitchLabPage,
  'radio-group': RadioGroupLabPage,
  'checkbox-group': CheckboxGroupLabPage,
  fieldset: FieldsetLabPage,
  'input-tree': InputTreeLabPage,
  'tree-select': TreeSelectLabPage,
  'tag-list': TagListLabPage,
  'key-value': KeyValueLabPage,
  'array-editor': ArrayEditorLabPage,
  combo: ComboLabPage,
  'input-table': InputTableLabPage,
  transfer: TransferLabPage,
  picker: PickerLabPage,
  'condition-builder': ConditionBuilderLabPage,
  'object-field': ObjectFieldLabPage,
  'array-field': ArrayFieldLabPage,
  'variant-field': VariantFieldLabPage,
  'detail-field': DetailFieldLabPage,
  'detail-view': DetailViewLabPage,
  crud: CrudLabPage,
  table: TableLabPage,
  tree: TreeLabPage,
  'data-source': DataSourceLabPage,
  chart: ChartLabPage,
  list: ListLabPage,
  pagination: PaginationLabPage,
  statistics: StatisticsLabPage,
  'input-date': InputDateLabPage,
  'input-datetime': InputDatetimeLabPage,
  'input-time': InputTimeLabPage,
  'date-range': DateRangeLabPage,
  'input-month': InputMonthLabPage,
  'input-quarter': InputQuarterLabPage,
  'input-year': InputYearLabPage,
  'markdown-editor': MarkdownEditorLabPage,
  'input-file': InputFileLabPage,
  'input-image': InputImageLabPage,
  editor: EditorLabPage,
};
