// ── AUTO-GENERATED by flux-guide/scripts/generate-types.mjs ──
// Do not edit manually. Regenerate with: node flux-guide/scripts/generate-types.mjs

import type {
  AlertSchema,
  ArrayEditorSchema,
  ArrayFieldSchema,
  AudioSchema,
  BadgeSchema,
  ButtonGroupSchema,
  ButtonSchema,
  CardSchema,
  CardsSchema,
  CarouselSchema,
  ChartSchema,
  CheckboxGroupSchema,
  CheckboxSchema,
  CollapseSchema,
  ComboSchema,
  ConditionBuilderSchema,
  ContainerSchema,
  CountdownSchema,
  CrudSchema,
  DataSourceSchema,
  DateRangeSchema,
  DetailFieldSchema,
  DetailViewSchema,
  DialogSchema,
  DrawerSchema,
  DropdownButtonSchema,
  DynamicRendererSchema,
  EditorSchema,
  EmptySchema,
  FieldsetSchema,
  FlexSchema,
  FormSchema,
  FragmentSchema,
  GridSchema,
  HtmlSchema,
  IconSchema,
  ImageSchema,
  InfiniteScrollSchema,
  InputDateSchema,
  InputDatetimeSchema,
  InputEmailSchema,
  InputFileSchema,
  InputImageSchema,
  InputMonthSchema,
  InputNumberSchema,
  InputPasswordSchema,
  InputQuarterSchema,
  InputTableSchema,
  InputTextSchema,
  InputTimeSchema,
  InputTreeSchema,
  InputYearSchema,
  JsonViewSchema,
  KeyValueSchema,
  LinkSchema,
  ListSchema,
  LoopSchema,
  MappingSchema,
  MarkdownEditorSchema,
  MarkdownSchema,
  NoticeBarSchema,
  ObjectFieldSchema,
  PageSchema,
  PaginationSchema,
  PickerSchema,
  ProgressSchema,
  PullRefreshSchema,
  QrCodeSchema,
  RadioGroupSchema,
  ReactionSchema,
  RecurseSchema,
  ScopeDebugSchema,
  SelectSchema,
  SeparatorSchema,
  SpinnerSchema,
  StatisticsSchema,
  StatusSchema,
  StepsSchema,
  SwipeCellSchema,
  SwitchSchema,
  TableSchema,
  TabsSchema,
  TagListSchema,
  TextSchema,
  TextareaSchema,
  TimelineSchema,
  TransferSchema,
  TreeSchema,
  TreeSelectSchema,
  VariantFieldSchema,
  VideoSchema,
  WizardSchema,
} from './schema';

export type FluxSchema =
  | PageSchema
  | ContainerSchema
  | FragmentSchema
  | LoopSchema
  | RecurseSchema
  | FlexSchema
  | TextSchema
  | ButtonSchema
  | IconSchema
  | BadgeSchema
  | ScopeDebugSchema
  | DynamicRendererSchema
  | ReactionSchema
  | TabsSchema
  | DialogSchema
  | DrawerSchema
  | WizardSchema
  | GridSchema
  | CollapseSchema
  | ButtonGroupSchema
  | DropdownButtonSchema
  | StepsSchema
  | TimelineSchema
  | FormSchema
  | InputTextSchema
  | InputEmailSchema
  | InputPasswordSchema
  | SelectSchema
  | TextareaSchema
  | CheckboxSchema
  | SwitchSchema
  | RadioGroupSchema
  | CheckboxGroupSchema
  | InputNumberSchema
  | InputDateSchema
  | InputDatetimeSchema
  | InputTimeSchema
  | DateRangeSchema
  | InputMonthSchema
  | InputQuarterSchema
  | InputYearSchema
  | FieldsetSchema
  | MarkdownEditorSchema
  | InputTreeSchema
  | TreeSelectSchema
  | TagListSchema
  | KeyValueSchema
  | ArrayEditorSchema
  | ConditionBuilderSchema
  | ObjectFieldSchema
  | ArrayFieldSchema
  | VariantFieldSchema
  | DetailFieldSchema
  | DetailViewSchema
  | EditorSchema
  | InputFileSchema
  | InputImageSchema
  | ComboSchema
  | InputTableSchema
  | TransferSchema
  | PickerSchema
  | TableSchema
  | DataSourceSchema
  | ChartSchema
  | TreeSchema
  | ListSchema
  | CrudSchema
  | PaginationSchema
  | StatisticsSchema
  | SeparatorSchema
  | SpinnerSchema
  | ProgressSchema
  | EmptySchema
  | CardSchema
  | LinkSchema
  | ImageSchema
  | JsonViewSchema
  | MarkdownSchema
  | HtmlSchema
  | CardsSchema
  | AlertSchema
  | MappingSchema
  | StatusSchema
  | AudioSchema
  | VideoSchema
  | CarouselSchema
  | QrCodeSchema
  | PullRefreshSchema
  | InfiniteScrollSchema
  | SwipeCellSchema
  | CountdownSchema
  | NoticeBarSchema;

export interface FluxSchemaByType {
  'page': PageSchema;
  'container': ContainerSchema;
  'fragment': FragmentSchema;
  'loop': LoopSchema;
  'recurse': RecurseSchema;
  'flex': FlexSchema;
  'text': TextSchema;
  'button': ButtonSchema;
  'icon': IconSchema;
  'badge': BadgeSchema;
  'scope-debug': ScopeDebugSchema;
  'dynamic-renderer': DynamicRendererSchema;
  'reaction': ReactionSchema;
  'tabs': TabsSchema;
  'dialog': DialogSchema;
  'drawer': DrawerSchema;
  'wizard': WizardSchema;
  'grid': GridSchema;
  'collapse': CollapseSchema;
  'button-group': ButtonGroupSchema;
  'dropdown-button': DropdownButtonSchema;
  'steps': StepsSchema;
  'timeline': TimelineSchema;
  'form': FormSchema;
  'input-text': InputTextSchema;
  'input-email': InputEmailSchema;
  'input-password': InputPasswordSchema;
  'select': SelectSchema;
  'textarea': TextareaSchema;
  'checkbox': CheckboxSchema;
  'switch': SwitchSchema;
  'radio-group': RadioGroupSchema;
  'checkbox-group': CheckboxGroupSchema;
  'input-number': InputNumberSchema;
  'input-date': InputDateSchema;
  'input-datetime': InputDatetimeSchema;
  'input-time': InputTimeSchema;
  'date-range': DateRangeSchema;
  'input-month': InputMonthSchema;
  'input-quarter': InputQuarterSchema;
  'input-year': InputYearSchema;
  'fieldset': FieldsetSchema;
  'markdown-editor': MarkdownEditorSchema;
  'input-tree': InputTreeSchema;
  'tree-select': TreeSelectSchema;
  'tag-list': TagListSchema;
  'key-value': KeyValueSchema;
  'array-editor': ArrayEditorSchema;
  'condition-builder': ConditionBuilderSchema;
  'object-field': ObjectFieldSchema;
  'array-field': ArrayFieldSchema;
  'variant-field': VariantFieldSchema;
  'detail-field': DetailFieldSchema;
  'detail-view': DetailViewSchema;
  'editor': EditorSchema;
  'input-file': InputFileSchema;
  'input-image': InputImageSchema;
  'combo': ComboSchema;
  'input-table': InputTableSchema;
  'transfer': TransferSchema;
  'picker': PickerSchema;
  'table': TableSchema;
  'data-source': DataSourceSchema;
  'chart': ChartSchema;
  'tree': TreeSchema;
  'list': ListSchema;
  'crud': CrudSchema;
  'pagination': PaginationSchema;
  'statistics': StatisticsSchema;
  'separator': SeparatorSchema;
  'spinner': SpinnerSchema;
  'progress': ProgressSchema;
  'empty': EmptySchema;
  'card': CardSchema;
  'link': LinkSchema;
  'image': ImageSchema;
  'json-view': JsonViewSchema;
  'markdown': MarkdownSchema;
  'html': HtmlSchema;
  'cards': CardsSchema;
  'alert': AlertSchema;
  'mapping': MappingSchema;
  'status': StatusSchema;
  'audio': AudioSchema;
  'video': VideoSchema;
  'carousel': CarouselSchema;
  'qrcode': QrCodeSchema;
  'pull-refresh': PullRefreshSchema;
  'infinite-scroll': InfiniteScrollSchema;
  'swipe-cell': SwipeCellSchema;
  'countdown': CountdownSchema;
  'notice-bar': NoticeBarSchema;
}

export type {
  AlertSchema,
  ArrayEditorSchema,
  ArrayFieldSchema,
  AudioSchema,
  BadgeSchema,
  ButtonGroupSchema,
  ButtonSchema,
  CardSchema,
  CardsSchema,
  CarouselSchema,
  ChartSchema,
  CheckboxGroupSchema,
  CheckboxSchema,
  CollapseSchema,
  ComboSchema,
  ConditionBuilderSchema,
  ContainerSchema,
  CountdownSchema,
  CrudSchema,
  DataSourceSchema,
  DateRangeSchema,
  DetailFieldSchema,
  DetailViewSchema,
  DialogSchema,
  DrawerSchema,
  DropdownButtonSchema,
  DynamicRendererSchema,
  EditorSchema,
  EmptySchema,
  FieldsetSchema,
  FlexSchema,
  FormSchema,
  FragmentSchema,
  GridSchema,
  HtmlSchema,
  IconSchema,
  ImageSchema,
  InfiniteScrollSchema,
  InputDateSchema,
  InputDatetimeSchema,
  InputEmailSchema,
  InputFileSchema,
  InputImageSchema,
  InputMonthSchema,
  InputNumberSchema,
  InputPasswordSchema,
  InputQuarterSchema,
  InputTableSchema,
  InputTextSchema,
  InputTimeSchema,
  InputTreeSchema,
  InputYearSchema,
  JsonViewSchema,
  KeyValueSchema,
  LinkSchema,
  ListSchema,
  LoopSchema,
  MappingSchema,
  MarkdownEditorSchema,
  MarkdownSchema,
  NoticeBarSchema,
  ObjectFieldSchema,
  PageSchema,
  PaginationSchema,
  PickerSchema,
  ProgressSchema,
  PullRefreshSchema,
  QrCodeSchema,
  RadioGroupSchema,
  ReactionSchema,
  RecurseSchema,
  ScopeDebugSchema,
  SelectSchema,
  SeparatorSchema,
  SpinnerSchema,
  StatisticsSchema,
  StatusSchema,
  StepsSchema,
  SwipeCellSchema,
  SwitchSchema,
  TableSchema,
  TabsSchema,
  TagListSchema,
  TextSchema,
  TextareaSchema,
  TimelineSchema,
  TransferSchema,
  TreeSchema,
  TreeSelectSchema,
  VariantFieldSchema,
  VideoSchema,
  WizardSchema,
} from './schema';
