/* eslint-disable max-lines */
/**
 * AUTO-GENERATED by flux-guide/scripts/generate-types.mjs
 * Do not edit manually. Regenerate with: node flux-guide/scripts/generate-types.mjs
 *
 * Based on RendererDefinition.propContracts + .fields from source packages.
 */

import type {
  BaseSchema,
  BoundFieldSchemaBase,
  SchemaInput,
  SchemaValue,
  ActionSchema,
} from './common';

// ============================================================================
// Basic — structural/display, flux-renderers-basic
// ============================================================================

export interface PageSchema extends BaseSchema {
  type: 'page';
  body?: SchemaInput;
  header?: SchemaInput;
  footer?: SchemaInput;
  aside?: SchemaInput;
  subTitle?: SchemaValue;
  remark?: SchemaValue;
  asidePosition?: SchemaValue;
  asideResizable?: boolean;
  asideMinWidth?: SchemaValue;
  asideMaxWidth?: SchemaValue;
  asideSticky?: boolean;
  modalContainer?: SchemaValue;
  statusPath?: SchemaValue;
  asideClassName?: SchemaValue;
  bodyClassName?: SchemaValue;
  headerClassName?: SchemaValue;
  footerClassName?: SchemaValue;
  toolbarClassName?: SchemaValue;
}

export interface ContainerSchema extends BaseSchema {
  type: 'container';
  body?: SchemaInput;
  header?: SchemaInput;
  footer?: SchemaInput;
  direction?: SchemaValue;
  wrap?: boolean;
  align?: SchemaValue;
  gap?: SchemaValue;
  responsiveDirection?: SchemaValue;
  responsiveWrap?: SchemaValue;
  bodyClassName?: SchemaValue;
  headerClassName?: SchemaValue;
  footerClassName?: SchemaValue;
}

export interface FragmentSchema extends BaseSchema {
  type: 'fragment';
  body?: SchemaInput;
  isolate?: SchemaValue;
}

export interface LoopSchema extends BaseSchema {
  type: 'loop';
  empty?: SchemaInput;
  items?: SchemaValue;
  itemName?: SchemaValue;
  indexName?: SchemaValue;
  keyName?: SchemaValue;
  itemData?: SchemaValue;
  keyBy?: SchemaValue;
  body?: SchemaInput;
}

export interface RecurseSchema extends BaseSchema {
  type: 'recurse';
  items?: SchemaValue;
  itemName?: SchemaValue;
  indexName?: SchemaValue;
  keyName?: SchemaValue;
  itemData?: SchemaValue;
  keyBy?: SchemaValue;
  maxDepth?: SchemaValue;
}

export interface FlexSchema extends BaseSchema {
  type: 'flex';
  body?: SchemaInput;
  items?: SchemaInput;
  direction?: SchemaValue;
  wrap?: boolean;
  align?: SchemaValue;
  justify?: SchemaValue;
  alignContent?: SchemaValue;
  gap?: SchemaValue;
  responsiveDirection?: SchemaValue;
  responsiveWrap?: SchemaValue;
}

export interface TextSchema extends BaseSchema {
  type: 'text';
  text?: SchemaValue;
  body?: SchemaValue;
  tag?: SchemaValue;
  copyable?: boolean;
  maxLine?: SchemaValue;
  maxLineToggle?: boolean;
}

export interface ButtonSchema extends BaseSchema {
  type: 'button';
  variant?: "default" | "destructive" | "outline" | "secondary" | "ghost" | "link";
  size?: "default" | "xs" | "sm" | "lg" | "icon" | "icon-xs" | "icon-sm" | "icon-lg";
  loading?: boolean;
  onClick?: ActionSchema | ActionSchema[];
  icon?: string;
  rightIcon?: string;
  tooltip?: string;
  disabledTip?: string;
  tooltipPlacement?: SchemaValue;
  countDown?: SchemaValue;
  countDownTpl?: SchemaValue;
  countDownStorage?: SchemaValue;
  href?: SchemaValue;
  target?: SchemaValue;
  block?: boolean;
  active?: boolean;
}

export interface IconSchema extends BaseSchema {
  type: 'icon';
  icon?: SchemaValue;
  size?: SchemaValue;
  color?: SchemaValue;
}

export interface BadgeSchema extends BaseSchema {
  type: 'badge';
  text?: SchemaValue;
  level?: SchemaValue;
}

export interface ScopeDebugSchema extends BaseSchema {
  type: 'scope-debug';
  defaultExpand?: SchemaValue;
  dataPaths?: SchemaValue;
}

export interface DynamicRendererSchema extends BaseSchema {
  type: 'dynamic-renderer';
  loadAction?: SchemaValue;
  autoLoad?: boolean;
  body?: SchemaInput;
}

export interface ReactionSchema extends BaseSchema {
  type: 'reaction';
  watch?: SchemaValue;
  dependsOn?: SchemaValue;
  immediate?: SchemaValue;
  debounce?: SchemaValue;
  once?: SchemaValue;
  actions?: SchemaValue;
}

export interface DialogSchema extends BaseSchema {
  type: 'dialog';
  body?: SchemaInput;
  actions?: SchemaInput;
  header?: SchemaInput;
  footer?: SchemaInput;
  onOpen?: ActionSchema | ActionSchema[];
  onClose?: ActionSchema | ActionSchema[];
  onConfirm?: ActionSchema | ActionSchema[];
  open?: SchemaValue;
  defaultOpen?: boolean;
  statusPath?: SchemaValue;
  container?: SchemaValue;
  showMask?: boolean;
  closeOnEsc?: boolean;
  size?: "xs" | "sm" | "md" | "lg" | "xl" | "full";
  width?: string | number;
  height?: string | number;
  showCloseButton?: boolean;
  confirm?: boolean | string;
  isolate?: boolean;
  bodyClassName?: string;
  headerClassName?: string;
  footerClassName?: string;
  closeOnOutsideClick?: boolean;
  draggable?: boolean;
  allowFullscreen?: boolean;
}

export interface DrawerSchema extends BaseSchema {
  type: 'drawer';
  body?: SchemaInput;
  actions?: SchemaInput;
  header?: SchemaInput;
  footer?: SchemaInput;
  onOpen?: ActionSchema | ActionSchema[];
  onClose?: ActionSchema | ActionSchema[];
  onConfirm?: ActionSchema | ActionSchema[];
  open?: SchemaValue;
  defaultOpen?: boolean;
  statusPath?: SchemaValue;
  container?: SchemaValue;
  showMask?: boolean;
  closeOnEsc?: boolean;
  size?: "xs" | "sm" | "md" | "lg" | "xl" | "full";
  width?: string | number;
  height?: string | number;
  showCloseButton?: boolean;
  confirm?: boolean | string;
  isolate?: boolean;
  bodyClassName?: string;
  headerClassName?: string;
  footerClassName?: string;
  side?: SchemaValue;
  closeOnOutside?: boolean;
  resizable?: boolean;
}

export interface TabsSchema extends BaseSchema {
  type: 'tabs';
  toolbar?: SchemaInput;
  onChange?: ActionSchema | ActionSchema[];
  items?: unknown[];
  value?: SchemaValue;
  defaultValue?: SchemaValue;
  valueOwnership?: SchemaValue;
  valueStatePath?: SchemaValue;
  statusPath?: SchemaValue;
  orientation?: "horizontal" | "vertical";
  variant?: "default" | "line";
  tabsMode?: SchemaValue;
  sidePosition?: SchemaValue;
  closable?: boolean;
  draggable?: boolean;
  addable?: boolean;
  contentClassName?: SchemaValue;
  toolbarClassName?: SchemaValue;
}

// ============================================================================
// Layout — flux-renderers-layout
// ============================================================================

export interface WizardSchema extends BaseSchema {
  type: 'wizard';
  steps?: unknown[];
  value?: string | number;
  defaultValue?: string | number;
  statusPath?: string;
  mode?: SchemaValue;
  linear?: boolean;
  allowStepJump?: boolean;
  mountOnEnter?: boolean;
  unmountOnExit?: boolean;
  actionFinishLabel?: SchemaValue;
  actionNextLabel?: SchemaValue;
  actionPrevLabel?: SchemaValue;
  actionNextSaveLabel?: SchemaValue;
  onChange?: ActionSchema | ActionSchema[];
  onStepCommit?: ActionSchema | ActionSchema[];
  onComplete?: ActionSchema | ActionSchema[];
  onStepError?: ActionSchema | ActionSchema[];
}

export interface GridSchema extends BaseSchema {
  type: 'grid';
  items?: unknown[];
  columns?: number | string;
  responsiveColumns?: SchemaValue;
  gap?: number | string;
  autoFlow?: "row" | "column" | "dense" | "row dense" | "column dense";
  alignItems?: "start" | "end" | "center" | "stretch";
  justifyItems?: "start" | "end" | "center" | "stretch";
}

export interface CollapseSchema extends BaseSchema {
  type: 'collapse';
  items?: unknown[];
  value?: unknown;
  defaultValue?: unknown;
  valueOwnership?: "local" | "controlled" | "scope";
  valueStatePath?: string;
  multiple?: boolean;
  collapsible?: boolean;
  onChange?: ActionSchema | ActionSchema[];
}

export interface ButtonGroupSchema extends BaseSchema {
  type: 'button-group';
  items?: unknown[];
  orientation?: "horizontal" | "vertical";
  variant?: "default" | "outline" | "secondary" | "ghost" | "destructive" | "link";
  size?: "default" | "xs" | "sm" | "lg";
  selectionMode?: "none" | "single" | "multiple";
  value?: unknown;
  defaultValue?: unknown;
  onChange?: ActionSchema | ActionSchema[];
}

export interface DropdownButtonSchema extends BaseSchema {
  type: 'dropdown-button';
  icon?: string;
  variant?: "default" | "outline" | "secondary" | "ghost" | "destructive" | "link";
  size?: "default" | "xs" | "sm" | "lg";
  items?: unknown[];
  trigger?: "click" | "hover";
}

export interface StepsSchema extends BaseSchema {
  type: 'steps';
  items?: unknown[];
  value?: string | number;
  defaultValue?: string | number;
  valueOwnership?: "local" | "controlled" | "scope";
  valueStatePath?: string;
  orientation?: "horizontal" | "vertical";
  onChange?: ActionSchema | ActionSchema[];
}

export interface TimelineSchema extends BaseSchema {
  type: 'timeline';
  items?: unknown[];
  mode?: "left" | "right" | "alternate";
  orientation?: "horizontal" | "vertical";
  reverse?: boolean;
}

// ============================================================================
// Form — flux-renderers-form
// ============================================================================

export interface FormSchema extends BoundFieldSchemaBase {
  type: 'form';
  body?: SchemaInput;
  actions?: SchemaInput;
  autoInit?: boolean;
  initAction?: ActionSchema | ActionSchema[];
  loadAction?: ActionSchema | ActionSchema[];
  autoLoad?: boolean;
  submitAction?: ActionSchema | ActionSchema[];
  onSubmitSuccess?: ActionSchema | ActionSchema[];
  onSubmitError?: ActionSchema | ActionSchema[];
  onValidateError?: ActionSchema | ActionSchema[];
  statusPath?: string;
  valuesPath?: string;
  hiddenFieldPolicy?: {
    validateWhenHidden?: boolean;
    clearValueWhenHidden?: boolean;
  };
  gap?: unknown;
  bodyClassName?: string;
  actionsClassName?: string;
  columnCount?: number;
  submitScope?: "local" | "surface";
  submitOnChange?: boolean;
  preventEnterSubmit?: boolean;
  autoFocus?: boolean;
  scrollToFirstError?: boolean;
  static?: boolean;
  rules?: unknown[];
}

export interface FieldsetSchema extends BoundFieldSchemaBase {
  type: 'fieldset';
  collapsible?: boolean;
  collapsed?: boolean;
  columnCount?: SchemaValue;
  gap?: SchemaValue;
  body?: SchemaInput;
  bodyClassName?: SchemaValue;
  titleClassName?: SchemaValue;
}

export interface InputTextSchema extends BoundFieldSchemaBase {
  type: 'input-text';
  value?: SchemaValue;
  prefix?: SchemaValue;
  suffix?: SchemaValue;
  clearable?: boolean;
  trimContents?: boolean;
  showCounter?: boolean;
  nativeAutoComplete?: SchemaValue;
  inputMode?: SchemaValue;
  revealPassword?: boolean;
  placeholder?: SchemaValue;
  minLength?: SchemaValue;
  maxLength?: SchemaValue;
  pattern?: SchemaValue;
  validate?: {
    action?: unknown;
    debounce?: number;
    message?: string;
  };
  hiddenFieldPolicy?: SchemaValue;
  suggestSource?: SchemaValue;
  suggestDebounce?: SchemaValue;
  suggestTrigger?: SchemaValue;
  suggestMinInputLength?: SchemaValue;
  suggestTemplate?: SchemaInput;
  suggestEmpty?: SchemaValue;
}

export interface InputEmailSchema extends BoundFieldSchemaBase {
  type: 'input-email';
  value?: SchemaValue;
  prefix?: SchemaValue;
  suffix?: SchemaValue;
  clearable?: boolean;
  trimContents?: boolean;
  showCounter?: boolean;
  nativeAutoComplete?: SchemaValue;
  inputMode?: SchemaValue;
  revealPassword?: boolean;
  placeholder?: SchemaValue;
  minLength?: SchemaValue;
  maxLength?: SchemaValue;
  pattern?: SchemaValue;
  validate?: {
    action?: unknown;
    debounce?: number;
    message?: string;
  };
  hiddenFieldPolicy?: SchemaValue;
  suggestSource?: SchemaValue;
  suggestDebounce?: SchemaValue;
  suggestTrigger?: SchemaValue;
  suggestMinInputLength?: SchemaValue;
  suggestTemplate?: SchemaInput;
  suggestEmpty?: SchemaValue;
}

export interface InputPasswordSchema extends BoundFieldSchemaBase {
  type: 'input-password';
  value?: SchemaValue;
  prefix?: SchemaValue;
  suffix?: SchemaValue;
  clearable?: boolean;
  trimContents?: boolean;
  showCounter?: boolean;
  nativeAutoComplete?: SchemaValue;
  inputMode?: SchemaValue;
  revealPassword?: boolean;
  placeholder?: SchemaValue;
  minLength?: SchemaValue;
  maxLength?: SchemaValue;
  pattern?: SchemaValue;
  validate?: {
    action?: unknown;
    debounce?: number;
    message?: string;
  };
  hiddenFieldPolicy?: SchemaValue;
  suggestSource?: SchemaValue;
  suggestDebounce?: SchemaValue;
  suggestTrigger?: SchemaValue;
  suggestMinInputLength?: SchemaValue;
  suggestTemplate?: SchemaInput;
  suggestEmpty?: SchemaValue;
}

export interface SelectSchema extends BoundFieldSchemaBase {
  type: 'select';
  value?: SchemaValue;
  options?: SchemaValue;
  dict?: SchemaValue;
  groups?: SchemaValue;
  multiple?: boolean;
  searchable?: boolean;
  clearable?: boolean;
  filterOption?: SchemaValue;
  searchPlaceholder?: SchemaValue;
  noResultsText?: SchemaValue;
  noMatchText?: SchemaValue;
  virtual?: boolean;
  optionTemplate?: SchemaInput;
  searchSource?: unknown;
  searchMergeMode?: SchemaValue;
  validate?: {
    action?: unknown;
    debounce?: number;
    message?: string;
  };
}

export interface TextareaSchema extends BoundFieldSchemaBase {
  type: 'textarea';
  value?: SchemaValue;
  rows?: SchemaValue;
  minRows?: SchemaValue;
  maxRows?: SchemaValue;
  clearable?: boolean;
  trimContents?: boolean;
  showCounter?: boolean;
  placeholder?: SchemaValue;
  minLength?: SchemaValue;
  maxLength?: SchemaValue;
  pattern?: SchemaValue;
  validate?: {
    action?: unknown;
    debounce?: number;
    message?: string;
  };
  hiddenFieldPolicy?: SchemaValue;
}

export interface CheckboxSchema extends BoundFieldSchemaBase {
  type: 'checkbox';
  value?: SchemaValue;
  option?: SchemaValue;
  trueValue?: SchemaValue;
  falseValue?: SchemaValue;
}

export interface SwitchSchema extends BoundFieldSchemaBase {
  type: 'switch';
  value?: SchemaValue;
  option?: SchemaValue;
  trueValue?: SchemaValue;
  falseValue?: SchemaValue;
}

export interface RadioGroupSchema extends BoundFieldSchemaBase {
  type: 'radio-group';
  value?: SchemaValue;
  options?: SchemaValue;
  direction?: SchemaValue;
}

export interface CheckboxGroupSchema extends BoundFieldSchemaBase {
  type: 'checkbox-group';
  value?: SchemaValue;
  options?: SchemaValue;
  checkAll?: boolean;
  maxSelected?: SchemaValue;
  minSelected?: SchemaValue;
  direction?: SchemaValue;
}

export interface ButtonGroupSelectSchema extends BoundFieldSchemaBase {
  type: 'button-group-select';
  value?: SchemaValue;
  options?: SchemaValue;
  multiple?: boolean;
  direction?: SchemaValue;
  dict?: SchemaValue;
}

export interface InputNumberSchema extends BoundFieldSchemaBase {
  type: 'input-number';
  value?: SchemaValue;
  precisionMode?: SchemaValue;
}

export interface InputDateSchema extends BoundFieldSchemaBase {
  type: 'input-date';
  value?: SchemaValue;
  valueFormat?: SchemaValue;
  displayFormat?: SchemaValue;
  utc?: boolean;
  clearable?: boolean;
  placeholder?: SchemaValue;
  minDate?: SchemaValue;
  maxDate?: SchemaValue;
}

export interface InputDatetimeSchema extends BoundFieldSchemaBase {
  type: 'input-datetime';
  value?: SchemaValue;
  valueFormat?: SchemaValue;
  displayFormat?: SchemaValue;
  timeFormat?: SchemaValue;
  utc?: boolean;
  clearable?: boolean;
  placeholder?: SchemaValue;
  minDate?: SchemaValue;
  maxDate?: SchemaValue;
}

export interface InputTimeSchema extends BoundFieldSchemaBase {
  type: 'input-time';
  value?: SchemaValue;
  valueFormat?: SchemaValue;
  displayFormat?: SchemaValue;
  clearable?: boolean;
  placeholder?: SchemaValue;
  minTime?: SchemaValue;
  maxTime?: SchemaValue;
}

export interface DateRangeSchema extends BoundFieldSchemaBase {
  type: 'date-range';
  value?: SchemaValue;
  rangeKind?: SchemaValue;
  valueFormat?: SchemaValue;
  displayFormat?: SchemaValue;
  delimiter?: SchemaValue;
  utc?: boolean;
  clearable?: boolean;
  placeholder?: SchemaValue;
  minDate?: SchemaValue;
  maxDate?: SchemaValue;
  shortcuts?: SchemaValue;
}

export interface InputMonthSchema extends BoundFieldSchemaBase {
  type: 'input-month';
  value?: SchemaValue;
  selectionMode?: SchemaValue;
  valueFormat?: SchemaValue;
  displayFormat?: SchemaValue;
  delimiter?: SchemaValue;
  clearable?: boolean;
  placeholder?: SchemaValue;
  minDate?: SchemaValue;
  maxDate?: SchemaValue;
  shortcuts?: SchemaValue;
}

export interface InputQuarterSchema extends BoundFieldSchemaBase {
  type: 'input-quarter';
  value?: SchemaValue;
  selectionMode?: SchemaValue;
  valueFormat?: SchemaValue;
  displayFormat?: SchemaValue;
  delimiter?: SchemaValue;
  clearable?: boolean;
  placeholder?: SchemaValue;
  minDate?: SchemaValue;
  maxDate?: SchemaValue;
  shortcuts?: SchemaValue;
}

export interface InputYearSchema extends BoundFieldSchemaBase {
  type: 'input-year';
  value?: SchemaValue;
  selectionMode?: SchemaValue;
  valueFormat?: SchemaValue;
  displayFormat?: SchemaValue;
  delimiter?: SchemaValue;
  clearable?: boolean;
  placeholder?: SchemaValue;
  minDate?: SchemaValue;
  maxDate?: SchemaValue;
  shortcuts?: SchemaValue;
}

export interface MarkdownEditorSchema extends BoundFieldSchemaBase {
  type: 'markdown-editor';
  value?: SchemaValue;
  placeholder?: SchemaValue;
  viewMode?: SchemaValue;
  toolbar?: boolean;
}

export interface InputTreeSchema extends BoundFieldSchemaBase {
  type: 'input-tree';
  value?: SchemaValue;
  options?: SchemaValue;
  virtualThreshold?: SchemaValue;
  childrenSource?: unknown;
  searchSource?: unknown;
  enableNodePath?: boolean;
  pathSeparator?: SchemaValue;
}

export interface TreeSelectSchema extends BoundFieldSchemaBase {
  type: 'tree-select';
  value?: SchemaValue;
  options?: SchemaValue;
  virtualThreshold?: SchemaValue;
  childrenSource?: unknown;
  searchSource?: unknown;
  enableNodePath?: boolean;
  pathSeparator?: SchemaValue;
}

export interface TagListSchema extends BoundFieldSchemaBase {
  type: 'tag-list';
  value?: SchemaValue;
}

export interface KeyValueSchema extends BoundFieldSchemaBase {
  type: 'key-value';
  value?: SchemaValue;
}

export interface ArrayEditorSchema extends BoundFieldSchemaBase {
  type: 'array-editor';
  value?: SchemaValue;
}

export interface ConditionBuilderSchema extends BoundFieldSchemaBase {
  type: 'condition-builder';
  value?: SchemaValue;
}

export interface ObjectFieldSchema extends BoundFieldSchemaBase {
  type: 'object-field';
  value?: SchemaValue;
  body?: SchemaInput;
  transformInAction?: SchemaValue;
  transformOutAction?: SchemaValue;
}

export interface ArrayFieldSchema extends BoundFieldSchemaBase {
  type: 'array-field';
  value?: SchemaValue;
  itemKind?: SchemaValue;
  itemKey?: SchemaValue;
  addable?: SchemaValue;
  removable?: SchemaValue;
  removeWhen?: SchemaValue;
  scalarItemValidation?: SchemaValue;
  item?: SchemaInput;
}

export interface VariantFieldSchema extends BoundFieldSchemaBase {
  type: 'variant-field';
  value?: SchemaValue;
  variants?: unknown[];
  selector?: SchemaValue;
  selectorMode?: SchemaValue;
  defaultVariant?: SchemaValue;
  detectVariantAction?: ActionSchema | ActionSchema[];
  transformInAction?: SchemaValue;
  transformOutAction?: SchemaValue;
  validateValueAction?: SchemaValue;
}

export interface DetailFieldSchema extends BoundFieldSchemaBase {
  type: 'detail-field';
  viewer?: SchemaInput;
  content?: SchemaInput;
  value?: SchemaValue;
  triggerLabel?: SchemaValue;
  surface?: SchemaValue;
  transformInAction?: SchemaValue;
  validateValueAction?: SchemaValue;
  transformOutAction?: SchemaValue;
}

export interface DetailViewSchema extends BoundFieldSchemaBase {
  type: 'detail-view';
  viewer?: SchemaInput;
  content?: SchemaInput;
  value?: SchemaValue;
  scopePath?: SchemaValue;
  triggerLabel?: SchemaValue;
  surface?: SchemaValue;
  transformInAction?: SchemaValue;
  validateValueAction?: SchemaValue;
  transformOutAction?: SchemaValue;
}

export interface EditorSchema extends BoundFieldSchemaBase {
  type: 'editor';
  value?: SchemaValue;
  placeholder?: SchemaValue;
  toolbar?: SchemaValue;
  outputFormat?: SchemaValue;
}

export interface InputFileSchema extends BoundFieldSchemaBase {
  type: 'input-file';
  value?: SchemaValue;
  placeholder?: SchemaValue;
  multiple?: boolean;
  accept?: SchemaValue;
  maxFiles?: SchemaValue;
  maxSize?: SchemaValue;
  uploadAction?: unknown;
  deleteAction?: unknown;
  valueMode?: SchemaValue;
  buttonText?: SchemaValue;
  onReject?: ActionSchema | ActionSchema[];
  onDelete?: ActionSchema | ActionSchema[];
  onDeleteSuccess?: ActionSchema | ActionSchema[];
  onDeleteFail?: ActionSchema | ActionSchema[];
}

export interface InputImageSchema extends BoundFieldSchemaBase {
  type: 'input-image';
  value?: SchemaValue;
  placeholder?: SchemaValue;
  multiple?: boolean;
  accept?: SchemaValue;
  maxFiles?: SchemaValue;
  maxSize?: SchemaValue;
  uploadAction?: unknown;
  deleteAction?: unknown;
  valueMode?: SchemaValue;
  buttonText?: SchemaValue;
  onReject?: ActionSchema | ActionSchema[];
  onDelete?: ActionSchema | ActionSchema[];
  onDeleteSuccess?: ActionSchema | ActionSchema[];
  onDeleteFail?: ActionSchema | ActionSchema[];
  previewMode?: SchemaValue;
  crop?: SchemaValue;
}

export interface ComboSchema extends BoundFieldSchemaBase {
  type: 'combo';
  value?: SchemaValue;
  columnCount?: SchemaValue;
  addable?: boolean;
  removable?: boolean;
  reorderable?: boolean;
  minItems?: SchemaValue;
  maxItems?: SchemaValue;
  itemKey?: SchemaValue;
  removeWhen?: SchemaValue;
  onAdd?: ActionSchema | ActionSchema[];
  onRemove?: ActionSchema | ActionSchema[];
  onReorder?: ActionSchema | ActionSchema[];
  items?: SchemaInput;
}

export interface InputTableSchema extends BoundFieldSchemaBase {
  type: 'input-table';
  value?: SchemaValue;
  columns?: SchemaValue;
  rowKey?: SchemaValue;
  addable?: boolean;
  removable?: boolean;
  reorderable?: boolean;
  minItems?: SchemaValue;
  maxItems?: SchemaValue;
  removeWhen?: SchemaValue;
  onAdd?: ActionSchema | ActionSchema[];
  onRemove?: ActionSchema | ActionSchema[];
  onReorder?: ActionSchema | ActionSchema[];
  item?: SchemaInput;
}

export interface TransferSchema extends BoundFieldSchemaBase {
  type: 'transfer';
  value?: SchemaValue;
  options?: SchemaValue;
  multiple?: boolean;
  valueKey?: SchemaValue;
  labelKey?: SchemaValue;
  searchable?: boolean;
  searchOnly?: boolean;
  searchPlaceholder?: SchemaValue;
  checkAll?: boolean;
  checkAllLabel?: SchemaValue;
  clearable?: boolean;
  selectTitle?: SchemaValue;
  resultTitle?: SchemaValue;
  onAdd?: ActionSchema | ActionSchema[];
  onRemove?: ActionSchema | ActionSchema[];
  onChange?: ActionSchema | ActionSchema[];
  onSelectAll?: ActionSchema | ActionSchema[];
}

export interface PickerSchema extends BoundFieldSchemaBase {
  type: 'picker';
  value?: SchemaValue;
  options?: SchemaValue;
  loadAction?: unknown;
  labelResolveAction?: unknown;
  valueKey?: SchemaValue;
  labelKey?: SchemaValue;
  columns?: SchemaValue;
  searchable?: SchemaValue;
  autoFill?: SchemaValue;
  pickerDialog?: SchemaValue;
  multiple?: boolean;
  onPick?: ActionSchema | ActionSchema[];
}

export interface IconPickerSchema extends BoundFieldSchemaBase {
  type: 'icon-picker';
  value?: SchemaValue;
  placeholder?: SchemaValue;
  searchable?: boolean;
  clearable?: boolean;
  defaultValue?: SchemaValue;
}

// ============================================================================
// Data — flux-renderers-data
// ============================================================================

export interface TableSchema extends BaseSchema {
  type: 'table';
  source?: unknown;
  rowKey?: SchemaValue;
  columns?: unknown[];
  paginationOwnership?: "local" | "controlled" | "scope";
  selectionOwnership?: "local" | "controlled" | "scope";
  sortOwnership?: "local" | "controlled" | "scope";
  filterOwnership?: "local" | "controlled" | "scope";
  paginationStatePath?: SchemaValue;
  selectionStatePath?: SchemaValue;
  sortStatePath?: SchemaValue;
  filterStatePath?: SchemaValue;
  header?: SchemaValue | SchemaInput;
  footer?: SchemaValue | SchemaInput;
  loading?: SchemaValue;
  stripe?: SchemaValue;
  bordered?: SchemaValue;
  virtualThreshold?: SchemaValue;
  scrollHeight?: SchemaValue;
  autoFillHeight?: SchemaValue;
  columnSettings?: SchemaValue;
  responsive?: SchemaValue;
  columnResize?: boolean;
  affixHeader?: boolean;
  showHeader?: boolean;
  prefixRow?: SchemaValue;
  affixRow?: SchemaValue;
  combineNum?: SchemaValue;
  combineFromIndex?: SchemaValue;
  draggable?: boolean;
  orderField?: SchemaValue;
  orderOwnership?: SchemaValue;
  orderStatePath?: SchemaValue;
  rowChildrenField?: SchemaValue;
  childrenSource?: SchemaValue;
  columnWidthsOwnership?: SchemaValue;
  columnWidthsStatePath?: SchemaValue;
  multiSort?: boolean;
  pagination?: Record<string, unknown>;
  rowSelection?: Record<string, unknown>;
  expandable?: unknown;
  quickSaveAction?: unknown;
  quickSaveItemAction?: unknown;
  onRowClick?: ActionSchema | ActionSchema[];
  onSortChange?: ActionSchema | ActionSchema[];
  onFilterChange?: ActionSchema | ActionSchema[];
  onPageChange?: ActionSchema | ActionSchema[];
  onSelectionChange?: ActionSchema | ActionSchema[];
  onRefresh?: ActionSchema | ActionSchema[];
  empty?: SchemaValue | SchemaInput;
  loadingContent?: SchemaValue | SchemaInput;
}

export interface DataSourceSchema extends BaseSchema {
  type: 'data-source';
  action?: SchemaValue;
  args?: SchemaValue;
  formula?: SchemaValue;
  sendOn?: string;
  initFetch?: boolean;
  interval?: SchemaValue;
  stopWhen?: SchemaValue;
  silent?: boolean;
  mergeToScope?: boolean;
  mergeStrategy?: SchemaValue;
  mergeKey?: SchemaValue;
  statusPath?: SchemaValue;
  dependsOn?: SchemaValue;
  initialData?: SchemaValue;
  resultMapping?: SchemaValue;
}

export interface ChartSchema extends BaseSchema {
  type: 'chart';
  source?: SchemaValue;
  series?: SchemaValue;
  chartType?: SchemaValue;
  xAxis?: SchemaValue;
  yAxis?: SchemaValue;
  height?: SchemaValue;
  loading?: SchemaValue;
  empty?: SchemaValue | SchemaInput;
  legend?: SchemaValue;
  stacked?: SchemaValue;
  grid?: SchemaValue;
  colors?: SchemaValue;
  referenceLines?: SchemaValue;
  band?: SchemaValue;
  markers?: SchemaValue;
  onClick?: ActionSchema | ActionSchema[];
  onHover?: ActionSchema | ActionSchema[];
}

export interface TreeSchema extends BaseSchema {
  type: 'tree';
  childrenKey?: SchemaValue;
  labelField?: SchemaValue;
  keyField?: SchemaValue;
  empty?: SchemaValue | SchemaInput;
  initiallyExpanded?: SchemaValue;
  expandOnClickNode?: SchemaValue;
  statusPath?: SchemaValue;
  searchable?: boolean;
  showIcon?: boolean;
  iconField?: SchemaValue;
  showGuideLine?: boolean;
  node?: SchemaInput;
}

export interface ListSchema extends BaseSchema {
  type: 'list';
  items?: unknown[];
  selectionMode?: "none" | "single" | "multiple";
  keyField?: string;
  pagination?: Record<string, unknown>;
  paginationOwnership?: "local" | "controlled" | "scope";
  paginationStatePath?: string;
  pageSizeStatePath?: string;
  onItemClick?: ActionSchema | ActionSchema[];
  onSelectionChange?: ActionSchema | ActionSchema[];
  onPageChange?: ActionSchema | ActionSchema[];
  onLoadMore?: ActionSchema | ActionSchema[];
  item?: SchemaInput;
  empty?: SchemaValue | SchemaInput;
}

export interface PaginationSchema extends BaseSchema {
  type: 'pagination';
  currentPage?: number;
  pageSize?: number;
  total?: number;
  pageSizeOptions?: number[];
  mode?: "simple" | "with-page-size";
  statusPath?: string;
  onChange?: ActionSchema | ActionSchema[];
  onPageSizeChange?: ActionSchema | ActionSchema[];
}

export interface StatisticsSchema extends BaseSchema {
  type: 'statistics';
  total?: number;
}

export interface CrudSchema extends BaseSchema {
  type: 'crud';
  statusPath?: string;
  source?: unknown[] | unknown;
  columns?: unknown[];
  listMode?: "table" | "cards" | "list";
  card?: SchemaInput;
  item?: SchemaInput;
  rowKey?: string;
  selection?: Record<string, unknown>;
  selectionOwnership?: "local" | "controlled" | "scope";
  selectionStatePath?: string;
  paginationOwnership?: "local" | "controlled" | "scope";
  paginationStatePath?: string;
  sortOwnership?: "local" | "controlled" | "scope";
  sortStatePath?: string;
  filterOwnership?: "local" | "controlled" | "scope";
  filterStatePath?: string;
  pageField?: string;
  pageSizeField?: string;
  defaultParams?: Record<string, unknown>;
  syncLocation?: SchemaValue;
  columnSettings?: Record<string, unknown>;
  responsive?: SchemaValue;
  autoClearSelectionOnRefresh?: SchemaValue;
  autoGenerateQueryForm?: SchemaValue;
  clientMode?: SchemaValue;
  polling?: Record<string, unknown>;
  filterTogglable?: Record<string, unknown>;
  pagination?: {
    mode: "pages" | "infinite";
  };
  quickSaveAction?: unknown;
  quickSaveItemAction?: unknown;
  loadAction?: SchemaValue;
  loadAllData?: boolean;
  dataStatePath?: SchemaValue;
  autoJumpToTopOnPagerChange?: boolean;
  totalField?: SchemaValue;
  hideQuickSaveBtn?: boolean;
  queryForm?: Record<string, unknown>;
  queryFormRegion?: SchemaInput;
  toolbar?: SchemaInput;
  listActions?: SchemaInput;
  footerToolbar?: SchemaInput;
  empty?: SchemaValue | SchemaInput;
  onQuerySubmit?: ActionSchema | ActionSchema[];
  onQueryReset?: ActionSchema | ActionSchema[];
  onRowClick?: ActionSchema | ActionSchema[];
  onSelectionChange?: ActionSchema | ActionSchema[];
  onRefresh?: ActionSchema | ActionSchema[];
  onError?: ActionSchema | ActionSchema[];
  toolbarLayout?: Record<string, unknown>;
}

// ============================================================================
// Content/Display — flux-renderers-content
// ============================================================================

export interface SeparatorSchema extends BaseSchema {
  type: 'separator';
  orientation?: SchemaValue;
  decorative?: boolean;
}

export interface SpinnerSchema extends BaseSchema {
  type: 'spinner';
  size?: SchemaValue;
}

export interface ProgressSchema extends BaseSchema {
  type: 'progress';
  value?: SchemaValue;
  max?: SchemaValue;
  variant?: SchemaValue;
  showValue?: boolean;
}

export interface EmptySchema extends BaseSchema {
  type: 'empty';
  description?: SchemaValue | SchemaInput;
  image?: SchemaValue;
  actions?: SchemaInput;
}

export interface CardSchema extends BaseSchema {
  type: 'card';
  header?: SchemaInput;
  body?: SchemaInput;
  footer?: SchemaInput;
  actions?: SchemaInput;
  image?: SchemaValue;
  imageClassName?: SchemaValue;
  variant?: SchemaValue;
  onClick?: ActionSchema | ActionSchema[];
}

export interface LinkSchema extends BaseSchema {
  type: 'link';
  href?: SchemaValue;
  target?: SchemaValue;
  rel?: SchemaValue;
  onClick?: ActionSchema | ActionSchema[];
}

export interface ImageSchema extends BaseSchema {
  type: 'image';
  src?: SchemaValue;
  alt?: SchemaValue;
  preview?: boolean;
  fit?: SchemaValue;
  width?: SchemaValue;
  height?: SchemaValue;
  lazy?: boolean;
  fetcher?: SchemaValue;
  onClick?: ActionSchema | ActionSchema[];
  onLoadError?: ActionSchema | ActionSchema[];
}

export interface JsonViewSchema extends BaseSchema {
  type: 'json-view';
  value?: SchemaValue;
  collapsed?: SchemaValue;
  showCopy?: boolean;
  empty?: SchemaValue | SchemaInput;
}

export interface MarkdownSchema extends BaseSchema {
  type: 'markdown';
  content?: SchemaValue;
  src?: SchemaValue;
  allowHtml?: boolean;
  empty?: SchemaValue | SchemaInput;
}

export interface HtmlSchema extends BaseSchema {
  type: 'html';
  content?: SchemaValue;
  sanitize?: boolean;
  empty?: SchemaValue | SchemaInput;
}

export interface CardsSchema extends BaseSchema {
  type: 'cards';
  items?: unknown[];
  columns?: SchemaValue;
  selectionMode?: "none" | "single" | "multiple";
  keyField?: string;
  onItemClick?: ActionSchema | ActionSchema[];
  onSelectionChange?: ActionSchema | ActionSchema[];
  card?: SchemaInput;
  empty?: SchemaValue | SchemaInput;
}

export interface AlertSchema extends BaseSchema {
  type: 'alert';
  level?: "info" | "success" | "warning" | "error";
  icon?: string;
  closable?: boolean;
  body?: SchemaValue | SchemaInput;
  actions?: SchemaInput;
  onClose?: ActionSchema | ActionSchema[];
}

export interface MappingSchema extends BaseSchema {
  type: 'mapping';
  value?: unknown;
  map?: Record<string, unknown>;
  defaultLabel?: string;
  placeholder?: string;
  source?: SchemaValue;
  item?: SchemaInput;
}

export interface StatusSchema extends BaseSchema {
  type: 'status';
  value?: unknown;
  labelMap?: Record<string, string>;
  levelMap?: Record<string, string>;
  iconMap?: Record<string, string>;
  placeholder?: string;
}

export interface AudioSchema extends BaseSchema {
  type: 'audio';
  src?: SchemaValue;
  poster?: SchemaValue;
  autoPlay?: boolean;
  loop?: boolean;
  controls?: boolean;
  onLoadError?: ActionSchema | ActionSchema[];
}

export interface VideoSchema extends BaseSchema {
  type: 'video';
  src?: SchemaValue;
  poster?: SchemaValue;
  autoPlay?: boolean;
  loop?: boolean;
  controls?: boolean;
  muted?: boolean;
  width?: SchemaValue;
  height?: SchemaValue;
  onLoadError?: ActionSchema | ActionSchema[];
}

export interface CarouselSchema extends BaseSchema {
  type: 'carousel';
  items?: unknown[];
  autoPlay?: boolean;
  interval?: SchemaValue;
  loop?: boolean;
  controls?: boolean;
  indicators?: boolean;
  onChange?: ActionSchema | ActionSchema[];
}

export interface QrCodeSchema extends BaseSchema {
  type: 'qrcode';
  value?: SchemaValue;
  size?: SchemaValue;
  level?: SchemaValue;
  foreground?: SchemaValue;
  background?: SchemaValue;
  onLoadError?: ActionSchema | ActionSchema[];
}

export interface DiffViewSchema extends BaseSchema {
  type: 'diff-view';
  oldContent?: SchemaValue;
  newContent?: SchemaValue;
  middleContent?: SchemaValue;
  files?: SchemaValue;
  activeFileIndex?: SchemaValue;
  language?: SchemaValue;
  viewType?: SchemaValue;
  showLineNumbers?: boolean;
  showInlineDiff?: boolean;
  defaultCollapsedLines?: SchemaValue;
  wrapLines?: boolean;
  onLineClick?: ActionSchema | ActionSchema[];
  onHunkExpand?: ActionSchema | ActionSchema[];
  toggleViewType?: SchemaValue;
  setViewType?: SchemaValue;
  expandAll?: SchemaValue;
  collapseAll?: SchemaValue;
}

// ============================================================================
// Mobile — flux-renderers-mobile
// ============================================================================

export interface PullRefreshSchema extends BaseSchema {
  type: 'pull-refresh';
  body?: SchemaInput;
  direction?: SchemaValue;
  threshold?: SchemaValue;
  loadingText?: SchemaValue;
  pullingText?: SchemaValue;
  loosingText?: SchemaValue;
  successText?: SchemaValue;
  successDuration?: SchemaValue;
  animationDuration?: SchemaValue;
  onRefresh?: ActionSchema | ActionSchema[];
}

export interface InfiniteScrollSchema extends BaseSchema {
  type: 'infinite-scroll';
  body?: SchemaInput;
  distance?: SchemaValue;
  loadingText?: SchemaValue;
  finishedText?: SchemaValue;
  errorText?: SchemaValue;
  immediateCheck?: boolean;
  hasMore?: boolean;
  loading?: boolean;
  error?: SchemaValue;
  onLoadMore?: ActionSchema | ActionSchema[];
}

export interface SwipeCellSchema extends BaseSchema {
  type: 'swipe-cell';
  body?: SchemaInput;
  left?: SchemaInput;
  right?: SchemaInput;
  threshold?: SchemaValue;
  direction?: SchemaValue;
  closeOnOutside?: boolean;
  onAction?: ActionSchema | ActionSchema[];
  onOpen?: ActionSchema | ActionSchema[];
  onClose?: ActionSchema | ActionSchema[];
}

export interface CountdownSchema extends BaseSchema {
  type: 'countdown';
  time?: SchemaValue;
  targetTime?: SchemaValue;
  format?: SchemaValue;
  millisecond?: boolean;
  paused?: boolean;
  autoStart?: boolean;
  prefix?: SchemaValue;
  suffix?: SchemaValue;
  onFinish?: ActionSchema | ActionSchema[];
}

export interface NoticeBarSchema extends BaseSchema {
  type: 'notice-bar';
  text?: SchemaValue;
  scrollable?: boolean;
  speed?: SchemaValue;
  direction?: SchemaValue;
  loop?: boolean;
  closable?: boolean;
  icon?: SchemaValue;
  variant?: SchemaValue;
  onClick?: ActionSchema | ActionSchema[];
  onClose?: ActionSchema | ActionSchema[];
}

// ============================================================================
// Code Editor — flux-code-editor (lazy-loaded CodeMirror)
// ============================================================================

export interface CodeEditorSchema extends BaseSchema {
  type: 'code-editor';
  hint?: SchemaValue | SchemaInput;
  description?: SchemaValue | SchemaInput;
  remark?: SchemaValue;
  labelRemark?: SchemaValue;
  labelAlign?: SchemaValue;
  labelWidth?: SchemaValue;
  value?: string;
  diffValue?: string;
  colorize?: boolean;
  language?: string;
  mode?: string;
  placeholder?: string;
  readOnly?: boolean;
  required?: boolean;
  expressionConfig?: Record<string, unknown>;
  sqlConfig?: Record<string, unknown>;
  editorTheme?: string;
  lineNumbers?: boolean;
  folding?: boolean;
  autoHeight?: boolean;
  allowFullscreen?: boolean;
  options?: Record<string, unknown>;
  height?: unknown;
  width?: unknown;
  onChange?: ActionSchema | ActionSchema[];
  onFocus?: ActionSchema | ActionSchema[];
  onBlur?: ActionSchema | ActionSchema[];
  onEditorMount?: ActionSchema | ActionSchema[];
}

// ============================================================================
// Scheduling — flux-renderers-scheduling
// ============================================================================

export interface GanttSchema extends BaseSchema {
  type: 'gantt';
  tasks?: SchemaValue;
  links?: SchemaValue;
  resources?: SchemaValue;
  assignments?: SchemaValue;
  columns?: SchemaValue;
  zoomLevels?: SchemaValue;
  defaultZoom?: SchemaValue;
  cellWidth?: SchemaValue;
  taskBarHeight?: SchemaValue;
  showWeekends?: SchemaValue;
  showToday?: SchemaValue;
  draggable?: SchemaValue;
  editable?: SchemaValue;
  linkable?: SchemaValue;
  taskBar?: SchemaInput;
  toolbar?: SchemaInput;
  editor?: SchemaInput;
  empty?: SchemaInput;
  loading?: SchemaInput;
  onTaskClick?: ActionSchema | ActionSchema[];
  onTaskDoubleClick?: ActionSchema | ActionSchema[];
  onTaskDragEnd?: ActionSchema | ActionSchema[];
  onLinkClick?: ActionSchema | ActionSchema[];
  onLinkDragEnd?: ActionSchema | ActionSchema[];
  onEmptyCellClick?: ActionSchema | ActionSchema[];
  onZoomChange?: ActionSchema | ActionSchema[];
  onScroll?: ActionSchema | ActionSchema[];
  toolbarClassName?: SchemaValue;
  taskBarClassName?: SchemaValue;
  editorClassName?: SchemaValue;
  emptyClassName?: SchemaValue;
  zoomIn?: SchemaValue;
  zoomOut?: SchemaValue;
  scrollToToday?: SchemaValue;
  scrollToTask?: SchemaValue;
}

export interface KanbanSchema extends BaseSchema {
  type: 'kanban';
  configMap?: SchemaValue;
  columnsConfig?: SchemaValue;
  columnHeader?: SchemaInput;
  columnHeaderToolbar?: SchemaInput;
  cardTemplate?: SchemaInput;
  columnFooter?: SchemaInput;
  empty?: SchemaInput;
  loading?: SchemaInput;
  filterText?: SchemaValue;
  filterCard?: SchemaValue;
  filterTags?: SchemaValue;
  columnWidth?: SchemaValue;
  columnDraggable?: SchemaValue;
  draggable?: SchemaValue;
  wipStrict?: SchemaValue;
  collapsedStatePath?: SchemaValue;
  collapsedOwnership?: SchemaValue;
  columnHeaderClassName?: SchemaValue;
  cardClassName?: SchemaValue;
  columnFooterClassName?: SchemaValue;
  kanbanOwnership?: SchemaValue;
  kanbanStatePath?: SchemaValue;
  statusPath?: SchemaValue;
  onCardMove?: ActionSchema | ActionSchema[];
  onCardClick?: ActionSchema | ActionSchema[];
  onColumnReorder?: ActionSchema | ActionSchema[];
  onColumnClick?: ActionSchema | ActionSchema[];
  onCardAdd?: ActionSchema | ActionSchema[];
  onCardRemove?: ActionSchema | ActionSchema[];
  onColumnAdd?: ActionSchema | ActionSchema[];
}

export interface CalendarSchema extends BaseSchema {
  type: 'calendar';
  view?: SchemaValue;
  date?: SchemaValue;
  events?: SchemaValue;
  resources?: SchemaValue;
  firstDayOfWeek?: SchemaValue;
  showWeekends?: SchemaValue;
  maxConcurrent?: SchemaValue;
  eventTemplate?: SchemaInput;
  loading?: SchemaInput;
  empty?: SchemaInput;
  body?: SchemaInput;
  headerClassName?: SchemaValue;
  eventClassName?: SchemaValue;
  emptyClassName?: SchemaValue;
  onEventClick?: ActionSchema | ActionSchema[];
  onDateChange?: ActionSchema | ActionSchema[];
  onViewChange?: ActionSchema | ActionSchema[];
  onEventChange?: ActionSchema | ActionSchema[];
  onEventCreate?: ActionSchema | ActionSchema[];
  onBatchSchedule?: ActionSchema | ActionSchema[];
  onImport?: ActionSchema | ActionSchema[];
  onImportError?: ActionSchema | ActionSchema[];
  onTimezoneChange?: ActionSchema | ActionSchema[];
  onGroupToggle?: ActionSchema | ActionSchema[];
  showCrossDayLines?: SchemaValue;
  timezoneSelector?: SchemaValue;
  batchScheduling?: SchemaValue;
  "resources[].resources"?: SchemaValue;
  "resources[].open"?: SchemaValue;
  viewOwnership?: SchemaValue;
  viewStatePath?: SchemaValue;
  dateOwnership?: SchemaValue;
  dateStatePath?: SchemaValue;
  locale?: SchemaValue;
  statusPath?: SchemaValue;
  loadAction?: ActionSchema | ActionSchema[];
  print?: SchemaValue;
  exportPNG?: SchemaValue;
  importICal?: SchemaValue;
  exportToICal?: SchemaValue;
}

export interface BarcodeInputSchema extends BaseSchema {
  type: 'barcode-input';
  placeholder?: SchemaValue;
  required?: boolean;
  readOnly?: boolean;
  clearable?: boolean;
  trimContents?: boolean;
  minLength?: SchemaValue;
  maxLength?: SchemaValue;
  pattern?: SchemaValue;
  validate?: SchemaValue;
  formats?: SchemaValue;
  continuousScan?: boolean;
  scanButton?: boolean;
  scanInterval?: SchemaValue;
  batchMode?: boolean;
  torchButton?: boolean;
  wasmUrl?: SchemaValue;
  scanButtonClassName?: SchemaValue;
  autoSubmit?: boolean;
  scanOnFocus?: boolean;
  onScan?: ActionSchema | ActionSchema[];
  onScanError?: ActionSchema | ActionSchema[];
}

// ============================================================================
// AI — flux-renderers-ai
// ============================================================================

export interface AiChatSchema extends BaseSchema {
  type: 'ai-chat';
  connector?: SchemaValue;
  placeholder?: SchemaValue;
  systemPrompt?: SchemaValue;
  submitType?: SchemaValue;
  maxLength?: SchemaValue;
  showWordLimit?: boolean;
  autofocus?: boolean;
  initialMessages?: SchemaValue;
  senderExtensions?: SchemaValue;
  conversationController?: SchemaValue;
  activeConversationId?: SchemaValue;
  engine?: SchemaValue;
  tools?: SchemaValue;
  toolExecutor?: SchemaValue;
  maxToolRounds?: SchemaValue;
  componentId?: SchemaValue;
  componentName?: SchemaValue;
  header?: SchemaInput;
  beforeMessages?: SchemaValue | SchemaInput;
  afterMessages?: SchemaValue | SchemaInput;
  emptyState?: SchemaValue | SchemaInput;
  footer?: SchemaInput;
  onResponseComplete?: ActionSchema | ActionSchema[];
  onError?: ActionSchema | ActionSchema[];
  onAbort?: ActionSchema | ActionSchema[];
  onConversationChange?: ActionSchema | ActionSchema[];
  branches?: SchemaValue;
  activeBranchId?: SchemaValue;
  onBranchChange?: ActionSchema | ActionSchema[];
}

export interface AiMessageListSchema extends BaseSchema {
  type: 'ai-message-list';
  autoScroll?: boolean;
  emptyRegion?: SchemaValue | SchemaInput;
}

export interface AiBubbleSchema extends BaseSchema {
  type: 'ai-bubble';
  message?: SchemaValue;
  placement?: SchemaValue;
  shape?: SchemaValue;
  showAvatar?: boolean;
  showTimestamp?: boolean;
  contentResolverName?: SchemaValue;
  branches?: SchemaValue;
  activeBranchId?: SchemaValue;
  onBranchChange?: ActionSchema | ActionSchema[];
}

export interface AiSenderSchema extends BaseSchema {
  type: 'ai-sender';
  placeholder?: SchemaValue;
  loading?: SchemaValue;
  autofocus?: boolean;
  maxLength?: SchemaValue;
  showWordLimit?: boolean;
  submitType?: SchemaValue;
  clearOnSubmit?: boolean;
  senderExtensions?: SchemaValue;
  onSubmit?: ActionSchema | ActionSchema[];
  onCancel?: ActionSchema | ActionSchema[];
  onChange?: ActionSchema | ActionSchema[];
}

export interface AiConversationsSchema extends BaseSchema {
  type: 'ai-conversations';
  conversations?: SchemaValue;
  activeId?: SchemaValue;
  showRenameControls?: boolean;
  onItemClick?: ActionSchema | ActionSchema[];
  onItemRename?: ActionSchema | ActionSchema[];
  onItemDelete?: ActionSchema | ActionSchema[];
  onCreate?: ActionSchema | ActionSchema[];
}

export interface AiWelcomeSchema extends BaseSchema {
  type: 'ai-welcome';
  description?: SchemaValue;
  icon?: SchemaValue;
  align?: SchemaValue;
  footer?: SchemaValue | SchemaInput;
}

export interface AiPromptsSchema extends BaseSchema {
  type: 'ai-prompts';
  items?: SchemaValue;
  layout?: SchemaValue;
  size?: SchemaValue;
  onSelect?: ActionSchema | ActionSchema[];
}

export interface AiFeedbackSchema extends BaseSchema {
  type: 'ai-feedback';
  message?: SchemaValue;
  actions?: SchemaValue;
  onAction?: ActionSchema | ActionSchema[];
}

export interface AiToolCallSchema extends BaseSchema {
  type: 'ai-tool-call';
  toolCall?: SchemaValue;
  state?: SchemaValue;
  defaultOpen?: boolean;
  onApproval?: ActionSchema | ActionSchema[];
}

export interface AiAttachmentsSchema extends BaseSchema {
  type: 'ai-attachments';
  value?: SchemaValue;
  mode?: SchemaValue;
  accept?: SchemaValue;
  multiple?: boolean;
  maxSize?: SchemaValue;
  maxFiles?: SchemaValue;
  enableDrop?: boolean;
  onChange?: ActionSchema | ActionSchema[];
  onError?: ActionSchema | ActionSchema[];
  onUpload?: ActionSchema | ActionSchema[];
}

export interface AiCitationsSchema extends BaseSchema {
  type: 'ai-citations';
  message?: SchemaValue;
  sources?: SchemaValue;
  mode?: SchemaValue;
  onSourceClick?: ActionSchema | ActionSchema[];
}

export interface AiVoiceInputSchema extends BaseSchema {
  type: 'ai-voice-input';
  lang?: SchemaValue;
  continuous?: boolean;
  interimResults?: boolean;
  onResult?: ActionSchema | ActionSchema[];
  onError?: ActionSchema | ActionSchema[];
}

export interface AiTokenUsageSchema extends BaseSchema {
  type: 'ai-token-usage';
  message?: SchemaValue;
  usage?: SchemaValue;
  contextLimit?: SchemaValue;
  showCost?: boolean;
  onClick?: ActionSchema | ActionSchema[];
}

export interface AiSuggestionsSchema extends BaseSchema {
  type: 'ai-suggestions';
  items?: SchemaValue;
  overflowMode?: SchemaValue;
  maxVisible?: SchemaValue;
  onSelect?: ActionSchema | ActionSchema[];
}
