/* eslint-disable max-lines */
/**
 * AUTO-GENERATED by flux-guide/scripts/generate-types.mjs
 * Do not edit manually. Regenerate with: node flux-guide/scripts/generate-types.mjs
 *
 * Based on RendererDefinition.propContracts + .fields from source packages.
 */

import type {
  BaseSchema,
  BoundFieldSchemaBase,
  SchemaInput,
  SchemaValue,
  ActionSchema,
} from './common';

// ============================================================================
// Basic — structural/display, flux-renderers-basic
// ============================================================================

export interface PageSchema extends BaseSchema {
  type: 'page';
  body?: SchemaInput;
  header?: SchemaInput;
  footer?: SchemaInput;
  aside?: SchemaInput;
  subTitle?: SchemaValue;
  remark?: SchemaValue;
  asidePosition?: SchemaValue;
  modalContainer?: SchemaValue;
  statusPath?: SchemaValue;
}

export interface ContainerSchema extends BaseSchema {
  type: 'container';
  body?: SchemaInput;
  header?: SchemaInput;
  footer?: SchemaInput;
}

export interface FragmentSchema extends BaseSchema {
  type: 'fragment';
  body?: SchemaInput;
  isolate?: SchemaValue;
}

export interface LoopSchema extends BaseSchema {
  type: 'loop';
  empty?: SchemaInput;
  items?: SchemaValue;
  itemName?: SchemaValue;
  indexName?: SchemaValue;
  keyName?: SchemaValue;
  itemData?: SchemaValue;
  keyBy?: SchemaValue;
  body?: SchemaInput;
}

export interface RecurseSchema extends BaseSchema {
  type: 'recurse';
  items?: SchemaValue;
  itemName?: SchemaValue;
  indexName?: SchemaValue;
  keyName?: SchemaValue;
  itemData?: SchemaValue;
  keyBy?: SchemaValue;
  maxDepth?: SchemaValue;
}

export interface FlexSchema extends BaseSchema {
  type: 'flex';
  body?: SchemaInput;
  items?: SchemaInput;
}

export interface TextSchema extends BaseSchema {
  type: 'text';
  text?: SchemaValue;
  body?: SchemaValue;
  tag?: SchemaValue;
  copyable?: boolean;
  maxLine?: SchemaValue;
  maxLineToggle?: boolean;
}

export interface ButtonSchema extends BaseSchema {
  type: 'button';
  loading?: boolean;
  onClick?: ActionSchema | ActionSchema[];
  icon?: string;
  rightIcon?: string;
  tooltip?: string;
  disabledTip?: string;
  block?: boolean;
  active?: boolean;
  variant?: "default" | "destructive" | "outline" | "secondary" | "ghost" | "link";
  size?: "default" | "xs" | "sm" | "lg" | "icon" | "icon-xs" | "icon-sm" | "icon-lg";
}

export interface IconSchema extends BaseSchema {
  type: 'icon';
  icon?: SchemaValue;
  size?: SchemaValue;
  color?: SchemaValue;
}

export interface BadgeSchema extends BaseSchema {
  type: 'badge';
}

export interface ScopeDebugSchema extends BaseSchema {
  type: 'scope-debug';
  defaultExpand?: SchemaValue;
  dataPaths?: SchemaValue;
}

export interface DynamicRendererSchema extends BaseSchema {
  type: 'dynamic-renderer';
  loadAction?: SchemaValue;
  autoLoad?: boolean;
  body?: SchemaInput;
}

export interface ReactionSchema extends BaseSchema {
  type: 'reaction';
  watch?: SchemaValue;
  immediate?: SchemaValue;
  debounce?: SchemaValue;
  once?: SchemaValue;
  actions?: SchemaValue;
}

export interface TabsSchema extends BaseSchema {
  type: 'tabs';
  toolbar?: SchemaInput;
  onChange?: ActionSchema | ActionSchema[];
  items?: SchemaValue;
  value?: SchemaValue;
  defaultValue?: SchemaValue;
  valueOwnership?: SchemaValue;
  valueStatePath?: SchemaValue;
  statusPath?: SchemaValue;
  orientation?: "horizontal" | "vertical";
  variant?: "default" | "line";
  tabsMode?: SchemaValue;
  sidePosition?: SchemaValue;
  contentClassName?: SchemaValue;
  toolbarClassName?: SchemaValue;
}

export interface DialogSchema extends BaseSchema {
  type: 'dialog';
}

export interface DrawerSchema extends BaseSchema {
  type: 'drawer';
}

// ============================================================================
// Layout — flux-renderers-layout
// ============================================================================

export interface WizardSchema extends BaseSchema {
  type: 'wizard';
  steps?: unknown[];
  value?: string | number;
  defaultValue?: string | number;
  statusPath?: string;
  linear?: boolean;
  allowStepJump?: boolean;
  mountOnEnter?: boolean;
  unmountOnExit?: boolean;
  onChange?: ActionSchema | ActionSchema[];
  onStepCommit?: ActionSchema | ActionSchema[];
  onComplete?: ActionSchema | ActionSchema[];
  onStepError?: ActionSchema | ActionSchema[];
}

export interface GridSchema extends BaseSchema {
  type: 'grid';
  items?: unknown[];
  columns?: number | string;
  responsiveColumns?: SchemaValue;
  gap?: number | string;
  autoFlow?: "row" | "column" | "dense" | "row dense" | "column dense";
  alignItems?: "start" | "end" | "center" | "stretch";
  justifyItems?: "start" | "end" | "center" | "stretch";
}

export interface CollapseSchema extends BaseSchema {
  type: 'collapse';
  items?: unknown[];
  value?: unknown;
  defaultValue?: unknown;
  valueOwnership?: "local" | "controlled" | "scope";
  valueStatePath?: string;
  multiple?: boolean;
  collapsible?: boolean;
  onChange?: ActionSchema | ActionSchema[];
}

export interface ButtonGroupSchema extends BaseSchema {
  type: 'button-group';
  items?: unknown[];
  orientation?: "horizontal" | "vertical";
  variant?: "default" | "outline" | "secondary" | "ghost" | "destructive" | "link";
  size?: "default" | "xs" | "sm" | "lg";
  selectionMode?: "none" | "single" | "multiple";
  value?: unknown;
  defaultValue?: unknown;
  onChange?: ActionSchema | ActionSchema[];
}

export interface DropdownButtonSchema extends BaseSchema {
  type: 'dropdown-button';
  icon?: string;
  variant?: "default" | "outline" | "secondary" | "ghost" | "destructive" | "link";
  size?: "default" | "xs" | "sm" | "lg";
  items?: unknown[];
  trigger?: "click" | "hover";
}

export interface StepsSchema extends BaseSchema {
  type: 'steps';
  items?: unknown[];
  value?: string | number;
  defaultValue?: string | number;
  valueOwnership?: "local" | "controlled" | "scope";
  valueStatePath?: string;
  orientation?: "horizontal" | "vertical";
  onChange?: ActionSchema | ActionSchema[];
}

export interface TimelineSchema extends BaseSchema {
  type: 'timeline';
  items?: unknown[];
  mode?: "left" | "right" | "alternate";
  orientation?: "horizontal" | "vertical";
  reverse?: boolean;
}

// ============================================================================
// Form — flux-renderers-form
// ============================================================================

export interface FormSchema extends BoundFieldSchemaBase {
  type: 'form';
  body?: SchemaInput;
  actions?: SchemaInput;
  autoInit?: boolean;
  initAction?: ActionSchema | ActionSchema[];
  submitAction?: ActionSchema | ActionSchema[];
  onSubmitSuccess?: ActionSchema | ActionSchema[];
  onSubmitError?: ActionSchema | ActionSchema[];
  onValidateError?: ActionSchema | ActionSchema[];
  statusPath?: string;
  valuesPath?: string;
  hiddenFieldPolicy?: {
    validateWhenHidden?: boolean;
    clearValueWhenHidden?: boolean;
  };
  bodyClassName?: SchemaValue;
  actionsClassName?: SchemaValue;
  columnCount?: number;
  submitOnChange?: boolean;
  preventEnterSubmit?: boolean;
  autoFocus?: boolean;
  scrollToFirstError?: boolean;
  static?: boolean;
  rules?: unknown[];
}

export interface InputTextSchema extends BoundFieldSchemaBase {
  type: 'input-text';
}

export interface InputEmailSchema extends BoundFieldSchemaBase {
  type: 'input-email';
}

export interface InputPasswordSchema extends BoundFieldSchemaBase {
  type: 'input-password';
}

export interface SelectSchema extends BoundFieldSchemaBase {
  type: 'select';
}

export interface TextareaSchema extends BoundFieldSchemaBase {
  type: 'textarea';
}

export interface CheckboxSchema extends BoundFieldSchemaBase {
  type: 'checkbox';
}

export interface SwitchSchema extends BoundFieldSchemaBase {
  type: 'switch';
}

export interface RadioGroupSchema extends BoundFieldSchemaBase {
  type: 'radio-group';
}

export interface CheckboxGroupSchema extends BoundFieldSchemaBase {
  type: 'checkbox-group';
}

export interface InputNumberSchema extends BoundFieldSchemaBase {
  type: 'input-number';
}

export interface InputDateSchema extends BoundFieldSchemaBase {
  type: 'input-date';
}

export interface InputDatetimeSchema extends BoundFieldSchemaBase {
  type: 'input-datetime';
}

export interface InputTimeSchema extends BoundFieldSchemaBase {
  type: 'input-time';
}

export interface DateRangeSchema extends BoundFieldSchemaBase {
  type: 'date-range';
}

export interface InputMonthSchema extends BoundFieldSchemaBase {
  type: 'input-month';
}

export interface InputQuarterSchema extends BoundFieldSchemaBase {
  type: 'input-quarter';
}

export interface InputYearSchema extends BoundFieldSchemaBase {
  type: 'input-year';
}

export interface FieldsetSchema extends BoundFieldSchemaBase {
  type: 'fieldset';
  collapsible?: boolean;
  collapsed?: boolean;
  body?: SchemaInput;
}

export interface MarkdownEditorSchema extends BoundFieldSchemaBase {
  type: 'markdown-editor';
}

export interface InputTreeSchema extends BoundFieldSchemaBase {
  type: 'input-tree';
}

export interface TreeSelectSchema extends BoundFieldSchemaBase {
  type: 'tree-select';
}

export interface TagListSchema extends BoundFieldSchemaBase {
  type: 'tag-list';
}

export interface KeyValueSchema extends BoundFieldSchemaBase {
  type: 'key-value';
}

export interface ArrayEditorSchema extends BoundFieldSchemaBase {
  type: 'array-editor';
}

export interface ConditionBuilderSchema extends BoundFieldSchemaBase {
  type: 'condition-builder';
}

export interface ObjectFieldSchema extends BoundFieldSchemaBase {
  type: 'object-field';
}

export interface ArrayFieldSchema extends BoundFieldSchemaBase {
  type: 'array-field';
}

export interface VariantFieldSchema extends BoundFieldSchemaBase {
  type: 'variant-field';
}

export interface DetailFieldSchema extends BoundFieldSchemaBase {
  type: 'detail-field';
}

export interface DetailViewSchema extends BoundFieldSchemaBase {
  type: 'detail-view';
}

export interface EditorSchema extends BoundFieldSchemaBase {
  type: 'editor';
}

export interface InputFileSchema extends BoundFieldSchemaBase {
  type: 'input-file';
}

export interface InputImageSchema extends BoundFieldSchemaBase {
  type: 'input-image';
}

export interface ComboSchema extends BoundFieldSchemaBase {
  type: 'combo';
}

export interface InputTableSchema extends BoundFieldSchemaBase {
  type: 'input-table';
}

export interface TransferSchema extends BoundFieldSchemaBase {
  type: 'transfer';
}

export interface PickerSchema extends BoundFieldSchemaBase {
  type: 'picker';
}

// ============================================================================
// Data — flux-renderers-data
// ============================================================================

export interface TableSchema extends BaseSchema {
  type: 'table';
  source?: unknown;
  rowKey?: SchemaValue;
  columns?: unknown;
  paginationOwnership?: "local" | "controlled" | "scope";
  selectionOwnership?: "local" | "controlled" | "scope";
  sortOwnership?: "local" | "controlled" | "scope";
  filterOwnership?: "local" | "controlled" | "scope";
  paginationStatePath?: SchemaValue;
  selectionStatePath?: SchemaValue;
  sortStatePath?: SchemaValue;
  filterStatePath?: SchemaValue;
  header?: SchemaValue | SchemaInput;
  footer?: SchemaValue | SchemaInput;
  loading?: SchemaValue;
  stripe?: SchemaValue;
  bordered?: SchemaValue;
  virtualThreshold?: SchemaValue;
  scrollHeight?: SchemaValue;
  columnSettings?: SchemaValue;
  responsive?: SchemaValue;
  columnResize?: boolean;
  affixHeader?: boolean;
  prefixRow?: SchemaValue;
  affixRow?: SchemaValue;
  combineNum?: SchemaValue;
  draggable?: boolean;
  orderField?: SchemaValue;
  orderOwnership?: SchemaValue;
  orderStatePath?: SchemaValue;
  rowChildrenField?: SchemaValue;
  columnWidthsOwnership?: SchemaValue;
  columnWidthsStatePath?: SchemaValue;
  multiSort?: boolean;
  pagination?: Record<string, unknown>;
  rowSelection?: Record<string, unknown>;
  expandable?: Record<string, unknown>;
  quickSaveAction?: SchemaValue;
  quickSaveItemAction?: SchemaValue;
  onRowClick?: ActionSchema | ActionSchema[];
  onSortChange?: ActionSchema | ActionSchema[];
  onFilterChange?: ActionSchema | ActionSchema[];
  onPageChange?: ActionSchema | ActionSchema[];
  onSelectionChange?: ActionSchema | ActionSchema[];
  onRefresh?: ActionSchema | ActionSchema[];
  empty?: SchemaValue | SchemaInput;
  loadingContent?: SchemaValue | SchemaInput;
}

export interface DataSourceSchema extends BaseSchema {
  type: 'data-source';
  action?: SchemaValue;
  args?: SchemaValue;
  formula?: SchemaValue;
  sendOn?: string;
  initFetch?: boolean;
  interval?: SchemaValue;
  stopWhen?: SchemaValue;
  silent?: boolean;
  mergeToScope?: boolean;
  mergeStrategy?: SchemaValue;
  mergeKey?: SchemaValue;
  statusPath?: SchemaValue;
  dependsOn?: SchemaValue;
  initialData?: SchemaValue;
  resultMapping?: SchemaValue;
}

export interface ChartSchema extends BaseSchema {
  type: 'chart';
  source?: SchemaValue;
  series?: SchemaValue;
  chartType?: SchemaValue;
  xAxis?: SchemaValue;
  yAxis?: SchemaValue;
  height?: SchemaValue;
  loading?: SchemaValue;
  empty?: SchemaValue | SchemaInput;
  legend?: SchemaValue;
  stacked?: SchemaValue;
  grid?: SchemaValue;
  colors?: SchemaValue;
  onClick?: ActionSchema | ActionSchema[];
  onHover?: ActionSchema | ActionSchema[];
}

export interface TreeSchema extends BaseSchema {
  type: 'tree';
  childrenKey?: SchemaValue;
  labelField?: SchemaValue;
  keyField?: SchemaValue;
  empty?: SchemaValue | SchemaInput;
  initiallyExpanded?: SchemaValue;
  expandOnClickNode?: SchemaValue;
  statusPath?: SchemaValue;
  searchable?: boolean;
  showIcon?: boolean;
  iconField?: SchemaValue;
  showGuideLine?: boolean;
  node?: SchemaInput;
}

export interface ListSchema extends BaseSchema {
  type: 'list';
  items?: unknown[];
  selectionMode?: "none" | "single" | "multiple";
  keyField?: string;
  pagination?: Record<string, unknown>;
  paginationOwnership?: "local" | "controlled" | "scope";
  paginationStatePath?: string;
  pageSizeStatePath?: string;
  onItemClick?: ActionSchema | ActionSchema[];
  onSelectionChange?: ActionSchema | ActionSchema[];
  onPageChange?: ActionSchema | ActionSchema[];
  onLoadMore?: ActionSchema | ActionSchema[];
  item?: SchemaInput;
  empty?: SchemaValue | SchemaInput;
}

export interface CrudSchema extends BaseSchema {
  type: 'crud';
  statusPath?: string;
  source?: unknown[] | unknown;
  columns?: unknown;
  listMode?: "table" | "cards" | "list";
  card?: SchemaInput;
  item?: SchemaInput;
  rowKey?: string;
  selection?: Record<string, unknown>;
  selectionOwnership?: "local" | "controlled" | "scope";
  selectionStatePath?: string;
  paginationOwnership?: "local" | "controlled" | "scope";
  paginationStatePath?: string;
  sortOwnership?: "local" | "controlled" | "scope";
  sortStatePath?: string;
  filterOwnership?: "local" | "controlled" | "scope";
  filterStatePath?: string;
  pageField?: string;
  pageSizeField?: string;
  defaultParams?: Record<string, unknown>;
  syncLocation?: SchemaValue;
  columnSettings?: Record<string, unknown>;
  responsive?: SchemaValue;
  autoClearSelectionOnRefresh?: SchemaValue;
  autoGenerateQueryForm?: SchemaValue;
  clientMode?: SchemaValue;
  polling?: Record<string, unknown>;
  filterTogglable?: Record<string, unknown>;
  pagination?: {
    mode: "pages" | "infinite";
  };
  quickSaveAction?: SchemaValue;
  quickSaveItemAction?: SchemaValue;
  loadAction?: unknown;
  loadAllData?: boolean;
  dataStatePath?: SchemaValue;
  queryForm?: Record<string, unknown>;
  queryFormRegion?: SchemaInput;
  toolbar?: SchemaInput;
  listActions?: SchemaInput;
  footerToolbar?: SchemaInput;
  empty?: SchemaValue | SchemaInput;
  onQuerySubmit?: ActionSchema | ActionSchema[];
  onQueryReset?: ActionSchema | ActionSchema[];
  onRowClick?: ActionSchema | ActionSchema[];
  onSelectionChange?: ActionSchema | ActionSchema[];
  onRefresh?: ActionSchema | ActionSchema[];
  onError?: ActionSchema | ActionSchema[];
  toolbarLayout?: Record<string, unknown>;
}

export interface ServiceSchema extends BaseSchema {
  type: 'service';
  items?: unknown;
  statusPath?: string;
  body?: SchemaInput;
  empty?: SchemaValue | SchemaInput;
  error?: SchemaValue | SchemaInput;
  loading?: SchemaValue | SchemaInput;
}

export interface PaginationSchema extends BaseSchema {
  type: 'pagination';
  currentPage?: number;
  pageSize?: number;
  total?: number;
  pageSizeOptions?: number[];
  mode?: "simple" | "with-page-size";
  statusPath?: string;
  onChange?: ActionSchema | ActionSchema[];
  onPageSizeChange?: ActionSchema | ActionSchema[];
}

export interface StatisticsSchema extends BaseSchema {
  type: 'statistics';
  total?: number;
}

// ============================================================================
// Content/Display — flux-renderers-content
// ============================================================================

export interface SeparatorSchema extends BaseSchema {
  type: 'separator';
  orientation?: SchemaValue;
  decorative?: boolean;
}

export interface SpinnerSchema extends BaseSchema {
  type: 'spinner';
  size?: SchemaValue;
}

export interface ProgressSchema extends BaseSchema {
  type: 'progress';
  value?: SchemaValue;
  max?: SchemaValue;
  variant?: SchemaValue;
  showValue?: boolean;
}

export interface EmptySchema extends BaseSchema {
  type: 'empty';
  description?: SchemaValue | SchemaInput;
  image?: SchemaValue;
  actions?: SchemaInput;
}

export interface CardSchema extends BaseSchema {
  type: 'card';
  header?: SchemaInput;
  body?: SchemaInput;
  footer?: SchemaInput;
  actions?: SchemaInput;
  image?: SchemaValue;
  imageClassName?: SchemaValue;
  variant?: SchemaValue;
  onClick?: ActionSchema | ActionSchema[];
}

export interface LinkSchema extends BaseSchema {
  type: 'link';
  href?: SchemaValue;
  target?: SchemaValue;
  rel?: SchemaValue;
  onClick?: ActionSchema | ActionSchema[];
}

export interface ImageSchema extends BaseSchema {
  type: 'image';
  src?: SchemaValue;
  alt?: SchemaValue;
  preview?: boolean;
  fit?: SchemaValue;
  width?: SchemaValue;
  height?: SchemaValue;
  lazy?: boolean;
  onClick?: ActionSchema | ActionSchema[];
  onLoadError?: ActionSchema | ActionSchema[];
}

export interface JsonViewSchema extends BaseSchema {
  type: 'json-view';
  value?: SchemaValue;
  collapsed?: SchemaValue;
  showCopy?: boolean;
  empty?: SchemaValue | SchemaInput;
}

export interface MarkdownSchema extends BaseSchema {
  type: 'markdown';
  content?: SchemaValue;
  allowHtml?: boolean;
  empty?: SchemaValue | SchemaInput;
}

export interface HtmlSchema extends BaseSchema {
  type: 'html';
  content?: SchemaValue;
  sanitize?: boolean;
  empty?: SchemaValue | SchemaInput;
}

export interface CardsSchema extends BaseSchema {
  type: 'cards';
  items?: unknown[];
  columns?: SchemaValue;
  selectionMode?: "none" | "single" | "multiple";
  keyField?: string;
  onItemClick?: ActionSchema | ActionSchema[];
  onSelectionChange?: ActionSchema | ActionSchema[];
  card?: SchemaInput;
  empty?: SchemaValue | SchemaInput;
}

export interface AlertSchema extends BaseSchema {
  type: 'alert';
  level?: "info" | "success" | "warning" | "error";
  icon?: string;
  closable?: boolean;
  body?: SchemaValue | SchemaInput;
  actions?: SchemaInput;
  onClose?: ActionSchema | ActionSchema[];
}

export interface MappingSchema extends BaseSchema {
  type: 'mapping';
  value?: unknown;
  map?: Record<string, unknown>;
  defaultLabel?: string;
  placeholder?: string;
  item?: SchemaInput;
}

export interface StatusSchema extends BaseSchema {
  type: 'status';
  value?: unknown;
  labelMap?: Record<string, string>;
  levelMap?: Record<string, string>;
  iconMap?: Record<string, string>;
  placeholder?: string;
}

export interface AudioSchema extends BaseSchema {
  type: 'audio';
  src?: SchemaValue;
  poster?: SchemaValue;
  autoPlay?: boolean;
  loop?: boolean;
  controls?: boolean;
  onLoadError?: ActionSchema | ActionSchema[];
}

export interface VideoSchema extends BaseSchema {
  type: 'video';
  src?: SchemaValue;
  poster?: SchemaValue;
  autoPlay?: boolean;
  loop?: boolean;
  controls?: boolean;
  muted?: boolean;
  onLoadError?: ActionSchema | ActionSchema[];
}

export interface CarouselSchema extends BaseSchema {
  type: 'carousel';
  items?: unknown[];
  autoPlay?: boolean;
  interval?: SchemaValue;
  loop?: boolean;
  controls?: boolean;
  indicators?: boolean;
  onChange?: ActionSchema | ActionSchema[];
}

export interface QrCodeSchema extends BaseSchema {
  type: 'qrcode';
  value?: SchemaValue;
  size?: SchemaValue;
  level?: SchemaValue;
  foreground?: SchemaValue;
  background?: SchemaValue;
  onLoadError?: ActionSchema | ActionSchema[];
}

// ============================================================================
// Mobile — flux-renderers-mobile
// ============================================================================

export interface PullRefreshSchema extends BaseSchema {
  type: 'pull-refresh';
  body?: SchemaInput;
  direction?: SchemaValue;
  threshold?: SchemaValue;
  loadingText?: SchemaValue;
  pullingText?: SchemaValue;
  loosingText?: SchemaValue;
  successText?: SchemaValue;
  successDuration?: SchemaValue;
  animationDuration?: SchemaValue;
  onRefresh?: ActionSchema | ActionSchema[];
}

export interface InfiniteScrollSchema extends BaseSchema {
  type: 'infinite-scroll';
  body?: SchemaInput;
  distance?: SchemaValue;
  loadingText?: SchemaValue;
  finishedText?: SchemaValue;
  errorText?: SchemaValue;
  immediateCheck?: boolean;
  hasMore?: boolean;
  loading?: boolean;
  error?: SchemaValue;
  onLoadMore?: ActionSchema | ActionSchema[];
}

export interface SwipeCellSchema extends BaseSchema {
  type: 'swipe-cell';
  body?: SchemaInput;
  left?: SchemaInput;
  right?: SchemaInput;
  threshold?: SchemaValue;
  direction?: SchemaValue;
  closeOnOutside?: boolean;
  onAction?: ActionSchema | ActionSchema[];
  onOpen?: ActionSchema | ActionSchema[];
  onClose?: ActionSchema | ActionSchema[];
}

export interface CountdownSchema extends BaseSchema {
  type: 'countdown';
  time?: SchemaValue;
  targetTime?: SchemaValue;
  format?: SchemaValue;
  millisecond?: boolean;
  paused?: boolean;
  autoStart?: boolean;
  prefix?: SchemaValue;
  suffix?: SchemaValue;
  onFinish?: ActionSchema | ActionSchema[];
}

export interface NoticeBarSchema extends BaseSchema {
  type: 'notice-bar';
  text?: SchemaValue;
  scrollable?: boolean;
  speed?: SchemaValue;
  direction?: SchemaValue;
  loop?: boolean;
  closable?: boolean;
  icon?: SchemaValue;
  variant?: SchemaValue;
  onClick?: ActionSchema | ActionSchema[];
  onClose?: ActionSchema | ActionSchema[];
}
